//! On-disk form of the authored composition profile, and the fold that puts it
//! into the simulation content hash.
//!
//! The solver crate owns the profile *type* and its validation rules; this
//! module owns its bytes. That split is deliberate: `observed_facility` never
//! reads a file, exactly as it never reads the compiled tile catalog.
//!
//! # Why the profile is hashed
//!
//! A facility is a pure function of `(seed, config, catalog, profile)`. Three of
//! those already agreed across a LAN session; the profile is the fourth, and
//! without it two peers running the same build but different profiles would
//! solve different facilities and silently desync. So the profile folds into
//! [`RuntimeHexCatalog::simulation_content_hash`], which the `Hello` handshake
//! already refuses a mismatch on.
//!
//! The fold is domain-separated rather than a plain concatenation, so a change
//! that moves a byte from the end of one artifact's hash to the start of the
//! other's cannot produce a colliding result.
//!
//! [`RuntimeHexCatalog::simulation_content_hash`]: crate::RuntimeHexCatalog

use std::path::Path;

use observed_facility::hex_wfc::profile::{HexCompositionProfile, ProfileDefect};
use sha2::{Digest, Sha256};

use crate::catalog::sha256;

/// The authored profile, beside the compiled catalog it is hashed with.
pub const COMPOSITION_PROFILE_FILE: &str = "composition_profile.ron";
/// Independently verifiable digest of [`COMPOSITION_PROFILE_FILE`].
pub const COMPOSITION_PROFILE_SHA_FILE: &str = "composition_profile.sha256";

/// Domain separator for the folded simulation content hash.
///
/// Bump the version suffix whenever the *set* of artifacts folded in changes,
/// so an old peer can never compute a matching hash by coincidence.
pub const SIMULATION_CONTENT_DOMAIN: &str = "observed2/simulation-content/v2";

const GENERATED_HEADER: &str =
    "// Generated by tilec. Edit through the composition studio, not this file.";

/// A validated profile together with the digest of its canonical bytes.
#[derive(Clone, Debug, PartialEq)]
pub struct CompositionBuild {
    pub profile: HexCompositionProfile,
    /// SHA-256 of [`to_pretty_ron`]'s output, lowercase hex.
    pub content_hash: String,
}

impl CompositionBuild {
    /// Hash `profile` and pair the two. Does not validate; callers that accept
    /// untrusted input go through [`parse_profile`].
    pub fn new(profile: HexCompositionProfile) -> Result<Self, CompositionError> {
        let content_hash = profile_content_hash(&profile)?;
        Ok(Self {
            profile,
            content_hash,
        })
    }

    /// The baseline profile — what a repository with no authored composition
    /// yet still hashes and ships.
    pub fn baseline() -> Result<Self, CompositionError> {
        Self::new(HexCompositionProfile::baseline())
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompositionError {
    Ron(String),
    /// The profile parsed but broke its own contract.
    Defects(Vec<ProfileDefect>),
    Io(String),
    /// The stored digest disagrees with the stored profile. Refusing to guess
    /// which is right is the whole point of the sidecar.
    SidecarDisagreement {
        file: String,
        stored: String,
        actual: String,
    },
}

impl std::fmt::Display for CompositionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Ron(detail) => write!(f, "composition profile is not valid RON: {detail}"),
            Self::Defects(defects) => {
                writeln!(f, "composition profile is invalid:")?;
                for defect in defects {
                    writeln!(f, "  - {defect}")?;
                }
                Ok(())
            }
            Self::Io(detail) => write!(f, "composition profile I/O: {detail}"),
            Self::SidecarDisagreement {
                file,
                stored,
                actual,
            } => write!(
                f,
                "{file} records {stored} but the profile hashes to {actual}; \
                 regenerate with `tilec profile-write` rather than editing either by hand"
            ),
        }
    }
}

impl std::error::Error for CompositionError {}

/// The profile's canonical bytes: LF-forced pretty RON, no header.
///
/// This is what gets hashed, so the header comment is deliberately excluded —
/// a comment change must not move the content hash.
pub fn to_canonical_ron(profile: &HexCompositionProfile) -> Result<String, CompositionError> {
    let config = ron::ser::PrettyConfig::default().new_line("\n".to_owned());
    ron::ser::to_string_pretty(profile, config)
        .map_err(|error| CompositionError::Ron(error.to_string()))
}

/// The bytes written to disk: the generated-file header, then the canonical RON.
pub fn to_pretty_ron(profile: &HexCompositionProfile) -> Result<String, CompositionError> {
    Ok(format!(
        "{GENERATED_HEADER}\n{}\n",
        to_canonical_ron(profile)?
    ))
}

/// SHA-256 of the profile's canonical bytes, lowercase hex.
pub fn profile_content_hash(profile: &HexCompositionProfile) -> Result<String, CompositionError> {
    Ok(sha256(to_canonical_ron(profile)?.as_bytes()))
}

/// Parse and validate a stored profile.
///
/// # Errors
///
/// [`CompositionError::Ron`] if the text is not a profile;
/// [`CompositionError::Defects`] listing every contract breach if it is.
pub fn parse_profile(text: &str) -> Result<HexCompositionProfile, CompositionError> {
    let profile: HexCompositionProfile =
        ron::from_str(text).map_err(|error| CompositionError::Ron(error.to_string()))?;
    profile.validate().map_err(CompositionError::Defects)?;
    Ok(profile)
}

/// Load the committed profile from a tile directory, checking its sidecar.
///
/// A missing profile is an error, never a silent fall back to the baseline: a
/// silent fallback is exactly the failure the content hash exists to catch,
/// because two peers would then disagree about a facility while both believing
/// they had loaded "the" composition.
pub fn load_profile(base: &Path) -> Result<CompositionBuild, CompositionError> {
    let profile_path = base.join(COMPOSITION_PROFILE_FILE);
    let text = std::fs::read_to_string(&profile_path)
        .map_err(|error| CompositionError::Io(format!("{}: {error}", profile_path.display())))?;
    let profile = parse_profile(&text)?;

    let sidecar_path = base.join(COMPOSITION_PROFILE_SHA_FILE);
    let sidecar = std::fs::read_to_string(&sidecar_path)
        .map_err(|error| CompositionError::Io(format!("{}: {error}", sidecar_path.display())))?;

    let actual = profile_content_hash(&profile)?;
    if sidecar.trim() != actual {
        return Err(CompositionError::SidecarDisagreement {
            file: COMPOSITION_PROFILE_SHA_FILE.to_string(),
            stored: sidecar.trim().to_string(),
            actual,
        });
    }
    Ok(CompositionBuild {
        profile,
        content_hash: actual,
    })
}

/// Write the profile and its sidecar, mirroring `write_catalog_build`'s
/// discipline: LF-forced canonical bytes, a generated-file header, and a
/// separately verifiable digest.
pub fn write_profile_build(build: &CompositionBuild, base: &Path) -> Result<(), CompositionError> {
    build
        .profile
        .validate()
        .map_err(CompositionError::Defects)?;

    let profile_path = base.join(COMPOSITION_PROFILE_FILE);
    std::fs::write(&profile_path, to_pretty_ron(&build.profile)?)
        .map_err(|error| CompositionError::Io(format!("{}: {error}", profile_path.display())))?;

    let sidecar_path = base.join(COMPOSITION_PROFILE_SHA_FILE);
    std::fs::write(&sidecar_path, format!("{}\n", build.content_hash))
        .map_err(|error| CompositionError::Io(format!("{}: {error}", sidecar_path.display())))?;
    Ok(())
}

/// Fold the two content artifacts into the one hash the LAN handshake gates on.
///
/// Domain-separated and length-delimited by the newlines: because both inputs
/// are fixed-width 64-character hex digests, no reshuffling of bytes between
/// them can produce the same preimage.
///
/// Note what is *not* here: the solver. This folds authored content only, so a
/// change to `hex_wfc` that makes a seed generate a different facility does not
/// move this hash, and two peers on different solver builds will shake hands
/// and then disagree about the map. The solver reaches this value through one
/// channel only - `COMPOSITION_PROFILE_VERSION`, which is stored in the profile
/// and therefore folded in as part of `profile_hex`. Bumping it on a solver
/// change is what turns that silent disagreement into a refused handshake.
#[must_use]
pub fn fold_simulation_content_hash(catalog_hex: &str, profile_hex: &str) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(SIMULATION_CONTENT_DOMAIN.as_bytes());
    hasher.update(b"\n");
    hasher.update(catalog_hex.as_bytes());
    hasher.update(b"\n");
    hasher.update(profile_hex.as_bytes());
    hasher.update(b"\n");
    hasher.finalize().into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use observed_facility::hex_wfc::HexArchetype;

    fn authored() -> HexCompositionProfile {
        let mut profile = HexCompositionProfile::baseline();
        profile.label = String::from("test");
        profile.archetype_bias = profile.archetype_bias.with(HexArchetype::Shaft, 0.5);
        profile
    }

    #[test]
    fn a_profile_round_trips_through_ron() {
        let profile = authored();
        let text = to_pretty_ron(&profile).expect("serializes");
        let parsed = parse_profile(&text).expect("parses");
        assert_eq!(parsed, profile);
    }

    #[test]
    fn the_baseline_profile_round_trips() {
        let profile = HexCompositionProfile::baseline();
        let text = to_pretty_ron(&profile).expect("serializes");
        assert_eq!(parse_profile(&text).expect("parses"), profile);
    }

    /// A pin set carries enums from three different crates through serde; if
    /// any of them lost its derive the round trip would drop authored intent.
    #[test]
    fn a_pin_set_round_trips_every_intent_shape() {
        use observed_facility::hex_wfc::HexSpace;
        use observed_facility::hex_wfc::profile::{HexPin, PinIntent, PinPortClass, PinSet};

        let mut profile = HexCompositionProfile::baseline();
        profile.pin_sets.push(PinSet {
            id: String::from("shapes"),
            note: String::from("one pin of every intent"),
            cols: 12,
            rows: 9,
            levels: 1,
            pins: vec![
                HexPin {
                    q: 1,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Space(HexSpace::Hall),
                },
                HexPin {
                    q: 2,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Archetype(HexArchetype::Shaft),
                },
                HexPin {
                    q: 3,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Forbid(vec![HexArchetype::Shaft, HexArchetype::RampUp]),
                },
                HexPin {
                    q: 4,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Ports {
                        doors: 0b0000_0101,
                        up: PinPortClass::Sealed,
                        down: PinPortClass::ShaftOpen,
                    },
                },
            ],
        });
        let text = to_pretty_ron(&profile).expect("serializes");
        assert_eq!(parse_profile(&text).expect("parses"), profile);
    }

    #[test]
    fn an_invalid_profile_is_rejected_with_its_defects() {
        let mut profile = HexCompositionProfile::baseline();
        profile.archetype_bias = profile.archetype_bias.with(HexArchetype::Shaft, 0.0);
        let text = to_pretty_ron(&profile).expect("serializes");
        match parse_profile(&text) {
            Err(CompositionError::Defects(defects)) => assert!(!defects.is_empty()),
            other => panic!("expected defects, got {other:?}"),
        }
    }

    #[test]
    fn the_hash_is_stable_across_a_reparse() {
        let profile = authored();
        let first = profile_content_hash(&profile).expect("hashes");
        let text = to_pretty_ron(&profile).expect("serializes");
        let reparsed = parse_profile(&text).expect("parses");
        assert_eq!(profile_content_hash(&reparsed).expect("hashes"), first);
    }

    /// The header is documentation, not content. If it were hashed, reflowing
    /// a comment would break LAN compatibility.
    #[test]
    fn the_generated_header_is_not_part_of_the_hash() {
        let profile = authored();
        let canonical = to_canonical_ron(&profile).expect("serializes");
        assert!(!canonical.contains("Generated by tilec"));
        assert_eq!(
            profile_content_hash(&profile).expect("hashes"),
            sha256(canonical.as_bytes())
        );
    }

    #[test]
    fn canonical_bytes_use_lf_only() {
        let canonical = to_canonical_ron(&authored()).expect("serializes");
        assert!(
            !canonical.contains('\r'),
            "CRLF in canonical bytes would make the hash platform-dependent"
        );
    }

    #[test]
    fn a_changed_profile_changes_the_hash() {
        let baseline = profile_content_hash(&HexCompositionProfile::baseline()).expect("hashes");
        let authored = profile_content_hash(&authored()).expect("hashes");
        assert_ne!(baseline, authored);
    }

    #[test]
    fn the_fold_changes_when_either_artifact_changes() {
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        let c = "c".repeat(64);
        let base = fold_simulation_content_hash(&a, &b);
        assert_ne!(base, fold_simulation_content_hash(&c, &b), "catalog moved");
        assert_ne!(base, fold_simulation_content_hash(&a, &c), "profile moved");
        assert_eq!(base, fold_simulation_content_hash(&a, &b), "and is stable");
    }

    /// The fold must not be a pass-through, or a peer could match on the
    /// catalog alone and skip the profile check entirely.
    #[test]
    fn the_fold_is_not_either_input() {
        let catalog = "a".repeat(64);
        let profile = "b".repeat(64);
        let hex = fold_simulation_content_hash(&catalog, &profile)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_ne!(hex, catalog);
        assert_ne!(hex, profile);
    }

    /// Swapping the two inputs must not collide — that is what the ordering
    /// plus domain separation buys.
    #[test]
    fn the_fold_is_order_sensitive() {
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        assert_ne!(
            fold_simulation_content_hash(&a, &b),
            fold_simulation_content_hash(&b, &a)
        );
    }

    #[test]
    fn write_then_load_round_trips_through_a_directory() {
        let dir = std::env::temp_dir().join("observed2_composition_round_trip");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");

        let build = CompositionBuild::new(authored()).expect("hashes");
        write_profile_build(&build, &dir).expect("writes");
        let loaded = load_profile(&dir).expect("loads");
        assert_eq!(loaded, build);

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_hand_edited_sidecar_is_refused() {
        let dir = std::env::temp_dir().join("observed2_composition_bad_sidecar");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");

        let build = CompositionBuild::new(authored()).expect("hashes");
        write_profile_build(&build, &dir).expect("writes");
        std::fs::write(
            dir.join(COMPOSITION_PROFILE_SHA_FILE),
            format!("{}\n", "0".repeat(64)),
        )
        .expect("clobbers the sidecar");

        match load_profile(&dir) {
            Err(CompositionError::SidecarDisagreement { .. }) => {}
            other => panic!("expected a sidecar disagreement, got {other:?}"),
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    fn committed_tiles() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../assets/tiles")
    }

    /// The committed profile and its sidecar must agree, or every runtime load
    /// fails. This is the same gate the compiled catalog already has.
    #[test]
    fn the_committed_profile_matches_its_sidecar() {
        load_profile(&committed_tiles()).expect("committed composition profile loads");
    }

    /// Slice 0 ships the substrate, not a composition change. If this starts
    /// failing, someone authored a real profile — which is fine, but it means
    /// the shipped facility changed and the layout evidence needs recapturing.
    #[test]
    fn the_committed_profile_is_still_the_baseline() {
        let build = load_profile(&committed_tiles()).expect("loads");
        assert!(
            build.profile.is_baseline(),
            "the committed profile is no longer the baseline: {:?}",
            build.profile.label
        );
    }

    /// The runtime's hash must be the fold, not either input — the check that
    /// a peer running a different composition is actually refused.
    #[test]
    fn the_runtime_catalog_hash_is_the_fold_of_both_artifacts() {
        let root = committed_tiles();
        let catalog_sidecar =
            std::fs::read_to_string(root.join("compiled_catalog.sha256")).expect("catalog sidecar");
        let profile = load_profile(&root).expect("profile loads");
        let expected = fold_simulation_content_hash(catalog_sidecar.trim(), &profile.content_hash);

        let catalog = crate::RuntimeHexCatalog::load(&root, &["liminal_grid"])
            .expect("runtime catalog loads");
        assert_eq!(
            catalog.simulation_content_hash, expected,
            "the runtime hash must fold catalog and composition"
        );
        assert_eq!(catalog.composition, profile.profile);
    }

    /// Arc S starts by pinning the exact content identity that LAN/replay
    /// compatibility and deterministic selection currently consume. A future
    /// Contract-Hat migration may intentionally move these values, but a
    /// behavior-preserving extraction must not.
    ///
    /// **Moved once, deliberately, 2026-08-08 (TR-10).** `hall_ramp` gained a
    /// traversal spine, which is content: the module changed, so its source
    /// hash changed and the catalog's did with it. The diff is 25 insertions
    /// and **zero deletions** in one `.map` — the ramp mass is byte-identical,
    /// so nothing about the geometry moved, only the annotation that says how
    /// to walk it. The profile hash is untouched, because the solve controls
    /// did not change.
    ///
    /// This gates LAN and replay compatibility: a client on the old catalog and
    /// one on this catalog will not play together, by design.
    #[test]
    fn committed_arc_s_catalog_identity_is_pinned() {
        // Moved when the hall family changed shape: the walk channel became
        // axial, and the wall that used to carry a doorway across every seam
        // was removed so a run of halls is one corridor rather than a string of
        // chambers. Eight hall modules, no others.
        const CATALOG_HASH: &str =
            "6ea4bfb1ce19003894c106d7ec04323a5a71ed693aee7c361d625547b2944145";
        const PROFILE_HASH: &str =
            "99e682b1f1348f9a7f8d2d10024a2d08b11dec0a917f51e41eb7801b5db84c2f";
        // Folds the catalog and the profile, so the ramp spine moves it too.
        // The profile side is unchanged; this is the catalog change arriving.
        const SIMULATION_HASH: &str =
            "1e9e8a90f1fbd539aa4cde6d6c66e3c4f2673151bcd30f12989d21a664e3082a";

        let root = committed_tiles();
        let compiled_text =
            std::fs::read_to_string(root.join("compiled_catalog.ron")).expect("catalog reads");
        let compiled =
            crate::CompiledTileCatalog::from_ron(&compiled_text).expect("catalog parses");
        let tower_modules = compiled
            .modules
            .iter()
            .filter(|module| module.archetype == "stair_tower")
            .collect::<Vec<_>>();
        assert_eq!(compiled.simulation_content_hash, CATALOG_HASH);
        assert_eq!(compiled.modules.len(), 125, "committed strict source count");
        assert_eq!(tower_modules.len(), 66, "one source per tower signature");
        assert!(
            tower_modules
                .iter()
                .all(|module| { module.register_scope == ["all"] && module.rotations == [0] })
        );

        let profile = load_profile(&root).expect("profile loads");
        assert_eq!(profile.content_hash, PROFILE_HASH);
        let simulation = fold_simulation_content_hash(CATALOG_HASH, PROFILE_HASH)
            .into_iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_eq!(simulation, SIMULATION_HASH);
    }

    #[test]
    fn a_missing_profile_is_an_error_not_a_silent_baseline() {
        let dir = std::env::temp_dir().join("observed2_composition_missing");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");
        assert!(matches!(load_profile(&dir), Err(CompositionError::Io(_))));
        std::fs::remove_dir_all(&dir).ok();
    }
}
