//! On-disk form of the authored composition profile, and the fold that puts it
//! into the simulation content hash.
//!
//! The solver crate owns the profile *type* and its validation rules; this
//! module owns its bytes. That split is deliberate: `observed_facility` never
//! reads a file, exactly as it never reads the compiled tile catalog.
//!
//! # Why the profile is hashed
//!
//! A facility is a pure function of `(seed, config, catalog, profile)`. Three of
//! those already agreed across a LAN session; the profile is the fourth, and
//! without it two peers running the same build but different profiles would
//! solve different facilities and silently desync. So the profile folds into
//! [`RuntimeHexCatalog::simulation_content_hash`], which the `Hello` handshake
//! already refuses a mismatch on.
//!
//! The fold is domain-separated rather than a plain concatenation, so a change
//! that moves a byte from the end of one artifact's hash to the start of the
//! other's cannot produce a colliding result.
//!
//! [`RuntimeHexCatalog::simulation_content_hash`]: crate::RuntimeHexCatalog

use std::path::Path;

use observed_facility::hex_wfc::profile::{HexCompositionProfile, ProfileDefect};
use sha2::{Digest, Sha256};

use crate::catalog::sha256;

/// The authored profile, beside the compiled catalog it is hashed with.
pub const COMPOSITION_PROFILE_FILE: &str = "composition_profile.ron";
/// Independently verifiable digest of [`COMPOSITION_PROFILE_FILE`].
pub const COMPOSITION_PROFILE_SHA_FILE: &str = "composition_profile.sha256";

/// Domain separator for the folded simulation content hash.
///
/// Bump the version suffix whenever the *set* of artifacts folded in changes,
/// so an old peer can never compute a matching hash by coincidence.
pub const SIMULATION_CONTENT_DOMAIN: &str = "observed2/simulation-content/v2";

const GENERATED_HEADER: &str =
    "// Generated by tilec. Edit through the composition studio, not this file.";

/// A validated profile together with the digest of its canonical bytes.
#[derive(Clone, Debug, PartialEq)]
pub struct CompositionBuild {
    pub profile: HexCompositionProfile,
    /// SHA-256 of [`to_pretty_ron`]'s output, lowercase hex.
    pub content_hash: String,
}

impl CompositionBuild {
    /// Hash `profile` and pair the two. Does not validate; callers that accept
    /// untrusted input go through [`parse_profile`].
    pub fn new(profile: HexCompositionProfile) -> Result<Self, CompositionError> {
        let content_hash = profile_content_hash(&profile)?;
        Ok(Self {
            profile,
            content_hash,
        })
    }

    /// The baseline profile — what a repository with no authored composition
    /// yet still hashes and ships.
    pub fn baseline() -> Result<Self, CompositionError> {
        Self::new(HexCompositionProfile::baseline())
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompositionError {
    Ron(String),
    /// The profile parsed but broke its own contract.
    Defects(Vec<ProfileDefect>),
    Io(String),
    /// The stored digest disagrees with the stored profile. Refusing to guess
    /// which is right is the whole point of the sidecar.
    SidecarDisagreement {
        file: String,
        stored: String,
        actual: String,
    },
}

impl std::fmt::Display for CompositionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Ron(detail) => write!(f, "composition profile is not valid RON: {detail}"),
            Self::Defects(defects) => {
                writeln!(f, "composition profile is invalid:")?;
                for defect in defects {
                    writeln!(f, "  - {defect}")?;
                }
                Ok(())
            }
            Self::Io(detail) => write!(f, "composition profile I/O: {detail}"),
            Self::SidecarDisagreement {
                file,
                stored,
                actual,
            } => write!(
                f,
                "{file} records {stored} but the profile hashes to {actual}; \
                 regenerate with `tilec profile-write` rather than editing either by hand"
            ),
        }
    }
}

impl std::error::Error for CompositionError {}

/// The profile's canonical bytes: LF-forced pretty RON, no header.
///
/// This is what gets hashed, so the header comment is deliberately excluded —
/// a comment change must not move the content hash.
pub fn to_canonical_ron(profile: &HexCompositionProfile) -> Result<String, CompositionError> {
    let config = ron::ser::PrettyConfig::default().new_line("\n".to_owned());
    ron::ser::to_string_pretty(profile, config)
        .map_err(|error| CompositionError::Ron(error.to_string()))
}

/// The bytes written to disk: the generated-file header, then the canonical RON.
pub fn to_pretty_ron(profile: &HexCompositionProfile) -> Result<String, CompositionError> {
    Ok(format!(
        "{GENERATED_HEADER}\n{}\n",
        to_canonical_ron(profile)?
    ))
}

/// SHA-256 of the profile's canonical bytes, lowercase hex.
pub fn profile_content_hash(profile: &HexCompositionProfile) -> Result<String, CompositionError> {
    Ok(sha256(to_canonical_ron(profile)?.as_bytes()))
}

/// Parse and validate a stored profile.
///
/// # Errors
///
/// [`CompositionError::Ron`] if the text is not a profile;
/// [`CompositionError::Defects`] listing every contract breach if it is.
pub fn parse_profile(text: &str) -> Result<HexCompositionProfile, CompositionError> {
    let profile: HexCompositionProfile =
        ron::from_str(text).map_err(|error| CompositionError::Ron(error.to_string()))?;
    profile.validate().map_err(CompositionError::Defects)?;
    Ok(profile)
}

/// Load the committed profile from a tile directory, checking its sidecar.
///
/// A missing profile is an error, never a silent fall back to the baseline: a
/// silent fallback is exactly the failure the content hash exists to catch,
/// because two peers would then disagree about a facility while both believing
/// they had loaded "the" composition.
pub fn load_profile(base: &Path) -> Result<CompositionBuild, CompositionError> {
    let profile_path = base.join(COMPOSITION_PROFILE_FILE);
    let text = std::fs::read_to_string(&profile_path)
        .map_err(|error| CompositionError::Io(format!("{}: {error}", profile_path.display())))?;
    let profile = parse_profile(&text)?;

    let sidecar_path = base.join(COMPOSITION_PROFILE_SHA_FILE);
    let sidecar = std::fs::read_to_string(&sidecar_path)
        .map_err(|error| CompositionError::Io(format!("{}: {error}", sidecar_path.display())))?;

    let actual = profile_content_hash(&profile)?;
    if sidecar.trim() != actual {
        return Err(CompositionError::SidecarDisagreement {
            file: COMPOSITION_PROFILE_SHA_FILE.to_string(),
            stored: sidecar.trim().to_string(),
            actual,
        });
    }
    Ok(CompositionBuild {
        profile,
        content_hash: actual,
    })
}

/// Write the profile and its sidecar, mirroring `write_catalog_build`'s
/// discipline: LF-forced canonical bytes, a generated-file header, and a
/// separately verifiable digest.
pub fn write_profile_build(build: &CompositionBuild, base: &Path) -> Result<(), CompositionError> {
    build
        .profile
        .validate()
        .map_err(CompositionError::Defects)?;

    let profile_path = base.join(COMPOSITION_PROFILE_FILE);
    std::fs::write(&profile_path, to_pretty_ron(&build.profile)?)
        .map_err(|error| CompositionError::Io(format!("{}: {error}", profile_path.display())))?;

    let sidecar_path = base.join(COMPOSITION_PROFILE_SHA_FILE);
    std::fs::write(&sidecar_path, format!("{}\n", build.content_hash))
        .map_err(|error| CompositionError::Io(format!("{}: {error}", sidecar_path.display())))?;
    Ok(())
}

/// Fold the two content artifacts into the one hash the LAN handshake gates on.
///
/// Domain-separated and length-delimited by the newlines: because both inputs
/// are fixed-width 64-character hex digests, no reshuffling of bytes between
/// them can produce the same preimage.
///
/// Note what is *not* here: the solver. This folds authored content only, so a
/// change to `hex_wfc` that makes a seed generate a different facility does not
/// move this hash, and two peers on different solver builds will shake hands
/// and then disagree about the map. The solver reaches this value through one
/// channel only - `COMPOSITION_PROFILE_VERSION`, which is stored in the profile
/// and therefore folded in as part of `profile_hex`. Bumping it on a solver
/// change is what turns that silent disagreement into a refused handshake.
#[must_use]
pub fn fold_simulation_content_hash(catalog_hex: &str, profile_hex: &str) -> [u8; 32] {
    let mut hasher = Sha256::new();
    hasher.update(SIMULATION_CONTENT_DOMAIN.as_bytes());
    hasher.update(b"\n");
    hasher.update(catalog_hex.as_bytes());
    hasher.update(b"\n");
    hasher.update(profile_hex.as_bytes());
    hasher.update(b"\n");
    hasher.finalize().into()
}

#[cfg(test)]
mod tests {
    use super::*;
    use observed_facility::hex_wfc::HexArchetype;

    fn authored() -> HexCompositionProfile {
        let mut profile = HexCompositionProfile::baseline();
        profile.label = String::from("test");
        profile.archetype_bias = profile.archetype_bias.with(HexArchetype::Shaft, 0.5);
        profile
    }

    #[test]
    fn a_profile_round_trips_through_ron() {
        let profile = authored();
        let text = to_pretty_ron(&profile).expect("serializes");
        let parsed = parse_profile(&text).expect("parses");
        assert_eq!(parsed, profile);
    }

    #[test]
    fn the_baseline_profile_round_trips() {
        let profile = HexCompositionProfile::baseline();
        let text = to_pretty_ron(&profile).expect("serializes");
        assert_eq!(parse_profile(&text).expect("parses"), profile);
    }

    /// A pin set carries enums from three different crates through serde; if
    /// any of them lost its derive the round trip would drop authored intent.
    #[test]
    fn a_pin_set_round_trips_every_intent_shape() {
        use observed_facility::hex_wfc::HexSpace;
        use observed_facility::hex_wfc::profile::{HexPin, PinIntent, PinPortClass, PinSet};

        let mut profile = HexCompositionProfile::baseline();
        profile.pin_sets.push(PinSet {
            id: String::from("shapes"),
            note: String::from("one pin of every intent"),
            cols: 12,
            rows: 9,
            levels: 1,
            pins: vec![
                HexPin {
                    q: 1,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Space(HexSpace::Hall),
                },
                HexPin {
                    q: 2,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Archetype(HexArchetype::Shaft),
                },
                HexPin {
                    q: 3,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Forbid(vec![HexArchetype::Shaft, HexArchetype::RampUp]),
                },
                HexPin {
                    q: 4,
                    r: 1,
                    level: 0,
                    intent: PinIntent::Ports {
                        doors: 0b0000_0101,
                        up: PinPortClass::Sealed,
                        down: PinPortClass::ShaftOpen,
                    },
                },
            ],
        });
        let text = to_pretty_ron(&profile).expect("serializes");
        assert_eq!(parse_profile(&text).expect("parses"), profile);
    }

    #[test]
    fn an_invalid_profile_is_rejected_with_its_defects() {
        let mut profile = HexCompositionProfile::baseline();
        profile.archetype_bias = profile.archetype_bias.with(HexArchetype::Shaft, 0.0);
        let text = to_pretty_ron(&profile).expect("serializes");
        match parse_profile(&text) {
            Err(CompositionError::Defects(defects)) => assert!(!defects.is_empty()),
            other => panic!("expected defects, got {other:?}"),
        }
    }

    #[test]
    fn the_hash_is_stable_across_a_reparse() {
        let profile = authored();
        let first = profile_content_hash(&profile).expect("hashes");
        let text = to_pretty_ron(&profile).expect("serializes");
        let reparsed = parse_profile(&text).expect("parses");
        assert_eq!(profile_content_hash(&reparsed).expect("hashes"), first);
    }

    /// The header is documentation, not content. If it were hashed, reflowing
    /// a comment would break LAN compatibility.
    #[test]
    fn the_generated_header_is_not_part_of_the_hash() {
        let profile = authored();
        let canonical = to_canonical_ron(&profile).expect("serializes");
        assert!(!canonical.contains("Generated by tilec"));
        assert_eq!(
            profile_content_hash(&profile).expect("hashes"),
            sha256(canonical.as_bytes())
        );
    }

    #[test]
    fn canonical_bytes_use_lf_only() {
        let canonical = to_canonical_ron(&authored()).expect("serializes");
        assert!(
            !canonical.contains('\r'),
            "CRLF in canonical bytes would make the hash platform-dependent"
        );
    }

    #[test]
    fn a_changed_profile_changes_the_hash() {
        let baseline = profile_content_hash(&HexCompositionProfile::baseline()).expect("hashes");
        let authored = profile_content_hash(&authored()).expect("hashes");
        assert_ne!(baseline, authored);
    }

    #[test]
    fn the_fold_changes_when_either_artifact_changes() {
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        let c = "c".repeat(64);
        let base = fold_simulation_content_hash(&a, &b);
        assert_ne!(base, fold_simulation_content_hash(&c, &b), "catalog moved");
        assert_ne!(base, fold_simulation_content_hash(&a, &c), "profile moved");
        assert_eq!(base, fold_simulation_content_hash(&a, &b), "and is stable");
    }

    /// The fold must not be a pass-through, or a peer could match on the
    /// catalog alone and skip the profile check entirely.
    #[test]
    fn the_fold_is_not_either_input() {
        let catalog = "a".repeat(64);
        let profile = "b".repeat(64);
        let hex = fold_simulation_content_hash(&catalog, &profile)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_ne!(hex, catalog);
        assert_ne!(hex, profile);
    }

    /// Swapping the two inputs must not collide — that is what the ordering
    /// plus domain separation buys.
    #[test]
    fn the_fold_is_order_sensitive() {
        let a = "a".repeat(64);
        let b = "b".repeat(64);
        assert_ne!(
            fold_simulation_content_hash(&a, &b),
            fold_simulation_content_hash(&b, &a)
        );
    }

    #[test]
    fn write_then_load_round_trips_through_a_directory() {
        let dir = std::env::temp_dir().join("observed2_composition_round_trip");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");

        let build = CompositionBuild::new(authored()).expect("hashes");
        write_profile_build(&build, &dir).expect("writes");
        let loaded = load_profile(&dir).expect("loads");
        assert_eq!(loaded, build);

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_hand_edited_sidecar_is_refused() {
        let dir = std::env::temp_dir().join("observed2_composition_bad_sidecar");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");

        let build = CompositionBuild::new(authored()).expect("hashes");
        write_profile_build(&build, &dir).expect("writes");
        std::fs::write(
            dir.join(COMPOSITION_PROFILE_SHA_FILE),
            format!("{}\n", "0".repeat(64)),
        )
        .expect("clobbers the sidecar");

        match load_profile(&dir) {
            Err(CompositionError::SidecarDisagreement { .. }) => {}
            other => panic!("expected a sidecar disagreement, got {other:?}"),
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    fn committed_tiles() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../assets/tiles")
    }

    /// The committed profile and its sidecar must agree, or every runtime load
    /// fails. This is the same gate the compiled catalog already has.
    #[test]
    fn the_committed_profile_matches_its_sidecar() {
        load_profile(&committed_tiles()).expect("committed composition profile loads");
    }

    /// Slice 0 ships the substrate, not a composition change. If this starts
    /// failing, someone authored a real profile — which is fine, but it means
    /// the shipped facility changed and the layout evidence needs recapturing.
    #[test]
    fn the_committed_profile_is_still_the_baseline() {
        let build = load_profile(&committed_tiles()).expect("loads");
        assert!(
            build.profile.is_baseline(),
            "the committed profile is no longer the baseline: {:?}",
            build.profile.label
        );
    }

    /// The runtime's hash must be the fold, not either input — the check that
    /// a peer running a different composition is actually refused.
    #[test]
    fn the_runtime_catalog_hash_is_the_fold_of_both_artifacts() {
        let root = committed_tiles();
        let catalog_sidecar =
            std::fs::read_to_string(root.join("compiled_catalog.sha256")).expect("catalog sidecar");
        let profile = load_profile(&root).expect("profile loads");
        let expected = fold_simulation_content_hash(catalog_sidecar.trim(), &profile.content_hash);

        let catalog = crate::RuntimeHexCatalog::load(&root, &["liminal_grid"])
            .expect("runtime catalog loads");
        assert_eq!(
            catalog.simulation_content_hash, expected,
            "the runtime hash must fold catalog and composition"
        );
        assert_eq!(catalog.composition, profile.profile);
    }

    /// Arc S starts by pinning the exact content identity that LAN/replay
    /// compatibility and deterministic selection currently consume. A future
    /// Contract-Hat migration may intentionally move these values, but a
    /// behavior-preserving extraction must not.
    ///
    /// **Moved once, deliberately, 2026-08-08 (TR-10).** `hall_ramp` gained a
    /// traversal spine, which is content: the module changed, so its source
    /// hash changed and the catalog's did with it. The diff is 25 insertions
    /// and **zero deletions** in one `.map` — the ramp mass is byte-identical,
    /// so nothing about the geometry moved, only the annotation that says how
    /// to walk it. The profile hash is untouched, because the solve controls
    /// did not change.
    ///
    /// This gates LAN and replay compatibility: a client on the old catalog and
    /// one on this catalog will not play together, by design.
    #[test]
    fn committed_arc_s_catalog_identity_is_pinned() {
        // Moved a fifth time by three authored tiles, and the profile side did
        // not move at all - which is the shape of an Arc T corpus change. 230 to
        // 239 modules. The last is `hall_straight_soffit`, and it is the first
        // cell in the corpus that is not 7.5 m tall - every hall tile before it,
        // generated and authored alike, put its ceiling at `LEVEL - FLOOR_TOP`
        // from ten separate call sites. Ceiling height is the one envelope
        // dimension the seam contract leaves free, and nothing had spent it.
        //
        // 238 modules, and three of them are the first **register-scoped**
        // authored masses in the corpus: a Monolith block, a Facet Monument
        // twelve-flute shaft and a Thinning stump, each reachable only in the
        // district it was cut for. Every authored hall before them is
        // register-agnostic - the same shape re-skinned ten ways.
        //
        // 235 modules: `hall_straight_datum`, a corridor that is not symmetric
        // under the half-turn swapping its doors; `hall_ramp_gallery`, a second
        // reading for the largest archetype that had only one; and three
        // hand-cut masses - a junction monolith, a sharp-turn splinter and a
        // shallow-turn boulder - which are the first modules in this corpus
        // whose shapes are written rather than called. No solve control
        // changed, so `COMPOSITION_PROFILE_VERSION` and the profile hash stand.
        //
        // The tower count is deliberately asserted alongside and is unmoved at
        // 171: authoring in the hall families must not disturb the vertical
        // corpus, and this is the line that says so.
        //
        // Moved a fourth time, and this is the one with the most behind it. Both
        // sides moved and for once the catalog side moved the most.
        //
        // The catalog gained 105 modules - every three- and four-door stair
        // tower, in each of the three vertical connectivities - taking it from
        // 125 to 230 and from 1.5 MB to 3.2 MB. Nothing that was already there
        // changed by a byte: the forge's door patterns are appended rather than
        // reordered, so all 66 committed towers reproduce exactly and the diff
        // is 105 new files and nothing else.
        //
        // Moved by twenty open halls, and by churn becoming a district
        // property.
        //
        // `hall_shell` fills every undoored sector solid, so a two-door cell is
        // a channel two and a quarter metres wide through fourteen metres of
        // mass. That is right for a district whose answer was weight and wrong
        // for four of the ten: the Back is a field rather than a route, the
        // Unwitnessed cannot be narrow, the Noon erased every landmark and a
        // channel *is* a landmark, and the Thin has no load-bearing walls at
        // all. Those four now get the five route shapes built as rooms - a
        // perimeter wall with apertures, same ports, same seam, same signature,
        // so the solver cannot tell and does not need to.
        //
        // Fourteen metres across against two and a quarter is the largest
        // single spatial difference available inside the contract, and it was
        // sitting behind a choice of construction recipe that had been in the
        // forge all along.
        //
        // Moved by the archetype sweep: the reclassification that makes the
        // authored corpus reachable at all.
        //
        // `placement_tile_archetype` is a closed match on eight names, so a
        // module whose archetype is not one of them can be authored, validated,
        // committed and shipped and the solver will still never ask for it. By
        // the last commit that was 117 of 326 modules - every gallery, every
        // one-off, and all seventy program tiles. A library the solver does not
        // shop from.
        //
        // A district dialect of an existing shape is a *variant* of that shape.
        // `hall_straight_soffit` had this right by accident and has been
        // placeable all along at `hall_straight` variant 3. Everything with the
        // same port signature now follows it: two opposed doors and sealed wall
        // elsewhere *is* `hall_straight`, whether the room is a corridor, a
        // canteen or a plant room. 278 of 326 reachable, from 209.
        //
        // The forty-eight left out are left out on purpose. One-door leaves
        // have no reachable archetype to be a variant of, and a gallery with no
        // lid is a shape the solver has no way to describe. Calling either a
        // `hall_straight` would be a lie about its geometry.
        //
        // The sweep also paid for itself immediately. Making a room a corridor
        // holds it to the corridor traversal gate, and the waiting area failed
        // it: a body could enter from the east and not from the west, because a
        // strip of benches parallel to a diagonal wall lay across the western
        // approach while clearing the eastern one. Every through-room now keeps
        // its fittings within `AISLE_DEPTH` of their own wall. That is a real
        // defect the tiles carried for six commits and only reachability
        // exposed.
        //
        // Moved by the office floor and the plant room - the sixth and seventh
        // program families, and the two ends of the module's range.
        //
        // The office is the one room where the *fabric* was disturbed rather
        // than the furniture. It is the only place in a building with two
        // removable surfaces - a ceiling you push a tile out of and a floor you
        // lift a panel out of - and both exist so somebody can get at the
        // services behind them. A tile pushed aside and never put back is the
        // most ordinary sight in a working building and the most final one in
        // an empty building: somebody was mid-job, and did not finish.
        //
        // The plant room is the control. Everything else here had people in it
        // and does not now, and the craft is making that difference visible. A
        // plant room never had anybody in it - somebody came twice a year,
        // looked at a gauge, and left. Strip the machines and it is the same
        // room: bare slab, holding-down bolts, services overhead, a drain, no
        // finishes because there was never anyone to finish it for. Walk from
        // the classroom, which is aimed at somebody, into this, which never
        // expected anyone, and the two kinds of emptiness are stated in one
        // threshold.
        //
        // Both families found the same contract edge the Welcome's dais did:
        // anything standing on something else that covers the cell centre reads
        // as a low ceiling over the floor. Partitions now go down to the
        // structural slab rather than sitting on the access floor, and stepped
        // plinths are nested blocks rather than stacked ones. Both are what the
        // real things do.
        //
        // Moved by the classroom in ten registers - the fifth program family,
        // and the only room in the corpus that *points*.
        //
        // The other four are shaped by an activity that is not happening. This
        // one is shaped by a person who is not there: the floor rakes toward
        // one end, the desks face that end, the framed recess is centred on it,
        // and on the dais there is a bolt pad where the lectern stood. Every
        // line in the plan converges on a rectangle of empty platform about the
        // size of a body. A canteen with no food in it is disused; a room where
        // three rows and a raked floor are still carefully aimed at one
        // unoccupied square metre is waiting.
        //
        // Two heights make a desk: a bench at 450 mm and a writing surface at
        // 730. That pair is what tells this from every other row of fixed
        // seating in a building, at a glance, from the door, and it is why the
        // desks are two members rather than one.
        //
        // Moved by the waiting area in ten registers - the fourth program
        // family, and the one the module was built to arrive at.
        //
        // Every other room in a building is *for* something: you eat here, you
        // wash here, you keep your coat here. This one is for delay. Its whole
        // purpose is the interval between arriving and being dealt with, so
        // even when full it was a room nobody wanted to be in and everybody was
        // in anyway. Emptying it does not change what it is for; it only
        // removes the thing that ever ended the wait.
        //
        // It is also the one room here whose furniture survives. Everywhere
        // else the fittings were carried off and the bolt pads are the
        // evidence, but waiting-room seating is beam-mounted steel bolted to
        // the slab - the one kind nobody could take and nobody wanted. So this
        // is not the shape of absent seating. It is rows of seats with nobody
        // in them, facing a shut window, which is worse.
        //
        // Moved by the locker corridor in ten registers, and by a correction
        // to the two program families already here.
        //
        // The correction first, because it is the larger fact. The restroom and
        // the refectory were authored with a counter at 48 units and a dado at
        // 44 - a counter two and a half metres off the floor, a dado at two and
        // a quarter, both picked by eye against a wall 128 units tall and both
        // wrong by a factor of about two and a half. The entire argument for
        // the program layer is that a basin is 850 mm in every building anyone
        // has ever built, so fittings that are not at that height are not doing
        // the job they were added to do.
        //
        // Correcting it says what the layer was groping toward. The facility is
        // built at roughly 1.6x a body - four-metre doorways, eight-metre
        // storeys - so true-scale fittings read as *small* in it. The locker
        // bank stands in the bottom quarter of the wall and the rest of the
        // wall runs up past it to nothing. The building is not at the scale of
        // the people who used it, and the fittings are the only evidence of
        // that, because they are the only things in the corpus made for a body.
        //
        // Moved by the refectory, in the same ten registers. Three things say
        // canteen and none of them is furniture: a tray rail, whose only
        // purpose is that something slides along it; a shutter, which is the
        // most complete statement of "this is over" that architecture has; and
        // six floor pads in rows, because three pads is an absence and six on a
        // grid is a seating plan, which is a number of people.
        //
        // It is also the one program room with two doors, on purpose. A
        // restroom you can walk out the far side of is a corridor with basins
        // in it; a canteen you can walk through is a canteen, because that is
        // what a canteen was - the one room in an institution that is both a
        // destination and a route, which is exactly why it is where everyone
        // met.
        //
        // Moved by the same restroom in all ten registers. Everything that
        // says *restroom* is fixed and identical across the set - four stalls
        // at the same pitch on the same wall, a counter, a splashback, three
        // bare pads, one door narrowed inboard. Only the way each district
        // builds those things varies, and holding the sentence still is what
        // turns the register vocabulary from ten moods into ten dialects.
        //
        // Each one is an argument. Monolith will not make a gap under
        // anything, so its stalls are piers. The Noon runs a soffit over the
        // row and removes the mirrors - the district that erased every landmark
        // was not going to leave the one fitting whose purpose is letting you
        // check you are still there. The Well, whose whole design is sightlines
        // between people, has no partitions at all: it did not solve privacy,
        // it abolished it.
        //
        // Moved by the first program tile, and by the module it opens.
        // `forge::program` is for the mundane fittings a facility is emptied
        // *of* - a liminal space is a lived-in space missing its living, and
        // every district so far is architecture that has never been used for
        // anything. The restroom is first because no room in a building is more
        // completely determined by bodies, so one with no bodies in it is the
        // shape of an absence rather than an empty box.
        //
        // It also supplies the thing all seven districts deliberately withhold.
        // A basin is 850 mm off the floor in every building ever made; one run
        // of them gives the facility a scale, and every space that refuses to
        // have one starts refusing it *against* something.
        //
        // Moved by five tiles that are ideas rather than decorations: a
        // transom (sight without traversal), a drop (walls and no floor
        // between them), a false depth (four frames receding faster than
        // perspective would take them, in a recess fifty units deep), a bore
        // (a hole through material rather than a room), and a reliquary (a
        // shelf carrying a model of the room the shelf is in).
        //
        // One of them records a gap rather than filling it. The transom's
        // aperture stops at the seam plane, and the contract allowed it because
        // a sealed face is only checked for the canonical door band - so it is
        // a very good-looking alcove until there is a `PortClass::Sight` for
        // the far side to match. That is the next real solver change worth
        // making: "hold a room you cannot enter" is a verb the game lacks.
        //
        // Moved by the Squint - a hall containing three blocks at three depths
        // that line up, from one floor plate and nowhere else, into the
        // outline of a doorway. Anamorphosis is four hundred years old and has
        // never had a better home than a facility that holds its shape only
        // where somebody is looking: the room contains a door that exists
        // exactly as long as it is observed from the one place it can be.
        //
        // Moved by the Vestry - one authored room, Monolith-scoped, that no
        // district plan asked for. It is a deathmatch room: a spiral of two
        // ramps onto a gallery that crosses over one of its own doorways, cover
        // set off the axis between the two doors, and a nosing under every lip
        // so the decks read as carried rather than glued. Nothing references
        // it, so dropping it is one line of `builders()` and a re-pin.
        //
        // Moved by Wave 1 of the district geometry plan - eight tiles, one per
        // district, each the cheapest thing that makes its fiction legible.
        // Four of them come out of one generalised gallery builder, because
        // the Index's low rail, the Unwitnessed's missing wedges and the Well's
        // landing over the drop are data, not code, and three builders would
        // have made those three facts look unrelated.
        //
        // The Index's parapet went from 20 units to 8 in the same move. Borges
        // says "very low", low is the word doing the work, and a tile whose
        // fiction is one number is a tile that should carry that number.
        //
        // Catalog side only again; the profile is unchanged at 5c1bc69d.
        //
        // Moved by three authored galleries - `hall_gallery` in the
        // Megastructure, Wellshaft and Infinite Gallery registers. A gallery is
        // a walkway round an open middle with no ceiling over the void, and it
        // exists because every other cell in the corpus carries a floor slab
        // *and* a ceiling slab: stack those and you get layered plates, not one
        // volume. A silo, a Babel shaft and a BLAME! well are the same claim -
        // one volume that several storeys look into - and none of them could be
        // composed until a cell could decline to have a lid.
        //
        // Catalog side only. The profile hash is unchanged at
        // 5c1bc69d..., because the solver's controls and its output for a fixed
        // seed did not move: these are authored modules that no WFC variant
        // draws yet. The simulation fold still moves, so this is still a LAN
        // lockout - a catalog-only change is exactly as breaking as a solver
        // one, and the fold is what says so.
        //
        // The profile side moved twice over. `route_corridors` is `true` now
        // rather than `false`, `carve_unrouted` is a new field, and
        // `COMPOSITION_PROFILE_VERSION` went to 4 because the solver's output
        // for a fixed seed moved - which it did in three separate ways: a wider
        // variant alphabet, a different default routing stage, and a different
        // lottery under both.
        //
        // Moved a third time by a schema change with no behaviour behind it: the
        // profile grew a `route_corridors` flag, default off. Worth recording
        // that `serde(default)` did *not* save it - this hash is taken over the
        // profile struct, not over the file, so any field added moves it whether
        // or not an old file still parses. A schema-only move is still a LAN
        // lockout, and there is no way to add a control without one.
        //
        // Moved before that when the collapse learned to draw the *space* before
        // the variant. The catalog is untouched - no tile changed - and the whole
        // move is on the profile side: a new `space_mix` field, and
        // `COMPOSITION_PROFILE_VERSION` at 3 because solver output moved.
        //
        // Moved before that when Keystone, Monitor and Recovery each gained a
        // second door.
        // Three room modules, no others: the geometry of a one-hex room is
        // unchanged and only the east face turned from solid wall into a framed
        // threshold. The profile side moved too, and for once not because a
        // solve control changed - `COMPOSITION_PROFILE_VERSION` went to 2
        // because the *solver's output* moved, and that constant is the only
        // channel by which such a change reaches this hash at all.
        const CATALOG_HASH: &str =
            "bb2495f41d74956a6f4f593cd4def36a26f24097bd2c7eea4a0b3ced81df9d74";
        const PROFILE_HASH: &str =
            "5c1bc69db058d4e3332e755326548f887d46f215d81fdeb454591cd9c2c0104e";
        // Folds the catalog and the profile. Both sides moved this time, which
        // is the point: a peer on the old build now fails the handshake instead
        // of joining and generating a different facility.
        const SIMULATION_HASH: &str =
            "0dba51401fe41e8faa8846e97cb4097e9f91581f0643667ec7bc20e9031442f9";

        let root = committed_tiles();
        let compiled_text =
            std::fs::read_to_string(root.join("compiled_catalog.ron")).expect("catalog reads");
        let compiled =
            crate::CompiledTileCatalog::from_ron(&compiled_text).expect("catalog parses");
        let tower_modules = compiled
            .modules
            .iter()
            .filter(|module| module.archetype == "stair_tower")
            .collect::<Vec<_>>();
        assert_eq!(compiled.simulation_content_hash, CATALOG_HASH);
        assert_eq!(compiled.modules.len(), 348, "committed strict source count");
        // 1 doorless + every one-to-four-door pattern, in three vertical
        // connectivities: (1 + 6 + 15 + 20 + 15) * 3. Was 66, when the family
        // stopped at two doors and there was no branching landing.
        assert_eq!(tower_modules.len(), 171, "one source per tower signature");
        assert!(
            tower_modules
                .iter()
                .all(|module| { module.register_scope == ["all"] && module.rotations == [0] })
        );

        let profile = load_profile(&root).expect("profile loads");
        assert_eq!(profile.content_hash, PROFILE_HASH);
        let simulation = fold_simulation_content_hash(CATALOG_HASH, PROFILE_HASH)
            .into_iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_eq!(simulation, SIMULATION_HASH);
    }

    #[test]
    fn a_missing_profile_is_an_error_not_a_silent_baseline() {
        let dir = std::env::temp_dir().join("observed2_composition_missing");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");
        assert!(matches!(load_profile(&dir), Err(CompositionError::Io(_))));
        std::fs::remove_dir_all(&dir).ok();
    }
}
