//! Declarative metadata table mapping profile scalars to interactive tunables.

use observed_facility::hex_wfc::profile::{HexCompositionProfile, SCORE_WEIGHT_MAX};
use observed_facility::hex_wfc::{HexArchetype, PROFILE_MAX, PROFILE_MIN};

use crate::StudioTab;

/// One editable scalar field inside a [`HexCompositionProfile`].
pub struct TunableField {
    pub label: &'static str,
    pub category: &'static str,
    pub tab: StudioTab,
    pub min: f64,
    pub max: f64,
    pub step: f64,
    pub get: fn(&HexCompositionProfile) -> f64,
    pub set: fn(&mut HexCompositionProfile, f64),
}

/// The 18 scalar tunable fields present in a [`HexCompositionProfile`].
///
/// 4 composition tendencies + 9 archetype biases + 5 score weights.
pub const TUNABLE_FIELDS: &[TunableField] = &[
    // --- Tendencies (4) ---
    TunableField {
        label: "vertical_center_boost",
        category: "Tendencies",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.tendencies.vertical_center_boost,
        set: |p, v| p.tendencies.vertical_center_boost = v,
    },
    TunableField {
        label: "vertical_edge_falloff",
        category: "Tendencies",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.tendencies.vertical_edge_falloff,
        set: |p, v| p.tendencies.vertical_edge_falloff = v,
    },
    TunableField {
        label: "room_low_level",
        category: "Tendencies",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.tendencies.room_low_level,
        set: |p, v| p.tendencies.room_low_level = v,
    },
    TunableField {
        label: "room_high_level",
        category: "Tendencies",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.tendencies.room_high_level,
        set: |p, v| p.tendencies.room_high_level = v,
    },
    // --- Archetype Biases (9) ---
    TunableField {
        label: "void_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.void,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Void, v),
    },
    TunableField {
        label: "room_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.room,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Room, v),
    },
    TunableField {
        label: "straight_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.straight,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Straight, v),
    },
    TunableField {
        label: "corner_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.corner,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Corner, v),
    },
    TunableField {
        label: "junction_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.junction,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Junction, v),
    },
    TunableField {
        label: "ramp_up_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.ramp_up,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::RampUp, v),
    },
    TunableField {
        label: "ramp_head_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.ramp_head,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::RampHead, v),
    },
    TunableField {
        label: "shaft_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.shaft,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Shaft, v),
    },
    TunableField {
        label: "expanse_bias",
        category: "Archetype Biases",
        tab: StudioTab::Tuning,
        min: PROFILE_MIN,
        max: PROFILE_MAX,
        step: 0.05,
        get: |p| p.archetype_bias.expanse,
        set: |p, v| p.archetype_bias = p.archetype_bias.with(HexArchetype::Expanse, v),
    },
    // --- Score Weights (5) ---
    TunableField {
        label: "connectivity_weight",
        category: "Score Weights",
        tab: StudioTab::Tuning,
        min: 0.0,
        max: SCORE_WEIGHT_MAX,
        step: 0.25,
        get: |p| p.score.connectivity,
        set: |p, v| p.score.connectivity = v,
    },
    TunableField {
        label: "elevation_weight",
        category: "Score Weights",
        tab: StudioTab::Tuning,
        min: 0.0,
        max: SCORE_WEIGHT_MAX,
        step: 0.25,
        get: |p| p.score.elevation,
        set: |p, v| p.score.elevation = v,
    },
    TunableField {
        label: "room_wholeness_weight",
        category: "Score Weights",
        tab: StudioTab::Tuning,
        min: 0.0,
        max: SCORE_WEIGHT_MAX,
        step: 0.25,
        get: |p| p.score.room_wholeness,
        set: |p, v| p.score.room_wholeness = v,
    },
    TunableField {
        label: "variety_weight",
        category: "Score Weights",
        tab: StudioTab::Tuning,
        min: 0.0,
        max: SCORE_WEIGHT_MAX,
        step: 0.25,
        get: |p| p.score.variety,
        set: |p, v| p.score.variety = v,
    },
    TunableField {
        label: "rhythm_weight",
        category: "Score Weights",
        tab: StudioTab::Tuning,
        min: 0.0,
        max: SCORE_WEIGHT_MAX,
        step: 0.25,
        get: |p| p.score.rhythm,
        set: |p, v| p.score.rhythm = v,
    },
];
