//! The hall family: eight single-cell corridor modules.
//!
//! A byte-exact port of the corresponding builders in `tools/tileforge.py`.
//! Same stable IDs, archetypes, variants, and ports, so every seam signature is
//! unchanged - these regenerate the committed files rather than replacing them.

use super::entities::{
    Meta, PORT_SHORT, ceiling_fixture, lateral_port, tile_cell_default, worldspawn,
};
use super::geometry::{
    FACE_NAMES, FLOOR_TOP, LEVEL, P2, WALL, band, door_wall_default, face_mid, hex_slab, prism,
    pylon, wall,
};

/// The line every generated file carries, so a reader who opens one knows not
/// to edit it.
const GENERATED_NOTE: &str =
    "// Generated by tools/tileforge.py - edit that script, not this file.\n";

#[must_use]
fn square(center: P2, half: f64) -> Vec<P2> {
    vec![
        (center.0 - half, center.1 - half),
        (center.0 + half, center.1 - half),
        (center.0 + half, center.1 + half),
        (center.0 - half, center.1 + half),
    ]
}

/// Floor and ceiling slabs, then a wall per face: a doorway where `door_faces`
/// says so, otherwise a sealed wall with a trim band.
#[must_use]
fn hall_shell(door_faces: &[usize]) -> String {
    let h = LEVEL;
    let mut brushes = String::from("// Floor and ceiling slabs (bevelled rims)\n");
    brushes.push_str(&hex_slab(0.0, FLOOR_TOP, 3.0, 0.0));
    brushes.push_str(&hex_slab(h - FLOOR_TOP, h, 0.0, 3.0));
    for (face, name) in FACE_NAMES.iter().enumerate() {
        if door_faces.contains(&face) {
            brushes.push_str(&format!("// Door wall: {name}\n"));
            brushes.push_str(&door_wall_default(face, 0.0, h));
        } else {
            brushes.push_str(&format!("// Sealed wall + trim: {name}\n"));
            brushes.push_str(&wall(face, 0.0, h));
            brushes.push_str(&band(face, WALL, WALL + 8.0, FLOOR_TOP, FLOOR_TOP + 12.0));
        }
    }
    brushes
}

/// Meta, footprint cell, and one door port per face.
///
/// East and west spell their names out while the others use the short form.
/// That asymmetry is in the committed files, so it is preserved rather than
/// tidied: the port name is part of the threshold identity.
#[must_use]
fn hall_meta_and_ports(name: &str, archetype: &str, door_faces: &[usize]) -> String {
    let mut out = Meta::cell(&format!("authored/{name}"), archetype, 0, 1, 10).emit();
    out.push_str(&tile_cell_default());
    for &face in door_faces {
        let short = if face == 0 || face == 3 {
            FACE_NAMES[face]
        } else {
            PORT_SHORT[face]
        };
        out.push_str(&lateral_port(
            face,
            "door",
            &format!("{short}_port"),
            0,
            0,
            0,
        ));
    }
    out
}

#[must_use]
pub fn hall_straight() -> String {
    let mut brushes = hall_shell(&[0, 3]);
    brushes.push_str("// Colonnade: two pillar pairs flanking the walk axis\n");
    for x in [-44.0, 44.0] {
        for y in [-34.0, 34.0] {
            brushes.push_str(&prism(
                &square((x, y), 6.0),
                FLOOR_TOP,
                LEVEL - FLOOR_TOP,
                None,
                3.0,
                0.0,
            ));
        }
    }
    let mut lights = String::new();
    for x in [-48.0, 48.0] {
        let (fixture, source) = ceiling_fixture(x, 0.0, LEVEL, 18.0, 10.0);
        brushes.push_str(&fixture);
        lights.push_str(&source);
    }
    let mut out = String::from("// Straight hall, doors east/west, colonnade interior.\n");
    out.push_str(GENERATED_NOTE);
    out.push_str(&worldspawn(&brushes));
    out.push_str(&hall_meta_and_ports(
        "hall_straight",
        "hall_straight",
        &[0, 3],
    ));
    out.push_str(&lights);
    out
}

#[must_use]
pub fn hall_cap() -> String {
    let mut brushes = hall_shell(&[0]);
    brushes.push_str("// Back-wall alcove: plinth and stele opposite the door\n");
    brushes.push_str(&prism(
        &[(-98.0, -34.0), (-72.0, -34.0), (-72.0, 34.0), (-98.0, 34.0)],
        FLOOR_TOP,
        24.0,
        None,
        3.0,
        0.0,
    ));
    brushes.push_str(&prism(
        &[(-96.0, -10.0), (-84.0, -10.0), (-84.0, 10.0), (-96.0, 10.0)],
        24.0,
        104.0,
        None,
        4.0,
        0.0,
    ));
    let (fixture, lights) = ceiling_fixture(-48.0, 0.0, LEVEL, 18.0, 10.0);
    brushes.push_str(&fixture);
    let mut out = String::from("// Dead-end cap, door east; alcove stele marks the sealed back.\n");
    out.push_str(GENERATED_NOTE);
    out.push_str(&worldspawn(&brushes));
    out.push_str(&hall_meta_and_ports("hall_cap", "hall_cap", &[0]));
    out.push_str(&lights);
    out
}

#[must_use]
fn hall_turn(name: &str, archetype: &str, second_face: usize) -> String {
    let mut brushes = hall_shell(&[0, second_face]);
    brushes.push_str("// Guide pillars opposite the elbow\n");
    let (m0, m1) = (face_mid(0), face_mid(second_face));
    let bis = (m0.0 + m1.0, m0.1 + m1.1);
    let length = bis.0.hypot(bis.1);
    let d = (bis.0 / length, bis.1 / length);
    let perp = (-d.1, d.0);
    for side in [-1.0, 1.0] {
        let center = (
            -d.0 * 40.0 + perp.0 * side * 40.0,
            -d.1 * 40.0 + perp.1 * side * 40.0,
        );
        brushes.push_str(&prism(
            &square(center, 6.5),
            FLOOR_TOP,
            LEVEL - FLOOR_TOP,
            None,
            3.0,
            0.0,
        ));
    }
    let (fixture, lights) = ceiling_fixture(0.0, 0.0, LEVEL, 18.0, 10.0);
    brushes.push_str(&fixture);
    let mut out = format!("// Corner hall, doors east/{}.\n", FACE_NAMES[second_face]);
    out.push_str(GENERATED_NOTE);
    out.push_str(&worldspawn(&brushes));
    out.push_str(&hall_meta_and_ports(name, archetype, &[0, second_face]));
    out.push_str(&lights);
    out
}

#[must_use]
pub fn hall_turn_60() -> String {
    hall_turn("hall_turn_60", "hall_turn_60", 5)
}

#[must_use]
pub fn hall_turn_120() -> String {
    hall_turn("hall_turn_120", "hall_turn_120", 4)
}

#[must_use]
fn hall_junction(name: &str, archetype: &str, door_faces: &[usize]) -> String {
    let mut brushes = hall_shell(door_faces);
    brushes.push_str("// Waypoint pylon with base collar\n");
    brushes.push_str(&pylon(14.0, FLOOR_TOP, LEVEL - FLOOR_TOP, 0.0, 5.0, 0.0));
    brushes.push_str(&pylon(24.0, FLOOR_TOP, 22.0, 0.0, 5.0, 0.0));
    let mut lights = String::new();
    for x in [-44.0, 44.0] {
        let (fixture, source) = ceiling_fixture(x, 0.0, LEVEL, 14.0, 8.0);
        brushes.push_str(&fixture);
        lights.push_str(&source);
    }
    let names: Vec<&str> = door_faces.iter().map(|&f| FACE_NAMES[f]).collect();
    let mut out = format!("// Junction hall, doors {}.\n", names.join(", "));
    out.push_str(GENERATED_NOTE);
    out.push_str(&worldspawn(&brushes));
    out.push_str(&hall_meta_and_ports(name, archetype, door_faces));
    out.push_str(&lights);
    out
}

#[must_use]
pub fn hall_junction_3way() -> String {
    hall_junction("hall_junction_3way", "hall_junction_3way", &[0, 3, 5])
}

#[must_use]
pub fn hall_junction_4way() -> String {
    hall_junction("hall_junction_4way", "hall_junction_4way", &[0, 2, 3, 5])
}

#[must_use]
pub fn hall_straight_buttressed() -> String {
    let mut brushes = hall_shell(&[0, 3]);
    brushes.push_str("// Grounded side buttresses keep the long axis open\n");
    for face in [1, 2, 4, 5] {
        brushes.push_str(&band(face, WALL, WALL + 18.0, FLOOR_TOP, 72.0));
    }
    let mut lights = String::new();
    for x in [-48.0, 48.0] {
        let (fixture, source) = ceiling_fixture(x, 0.0, LEVEL, 16.0, 9.0);
        brushes.push_str(&fixture);
        lights.push_str(&source);
    }
    let mut out =
        String::from("// Straight hall variant: structural side buttresses, clear E/W route.\n");
    out.push_str(GENERATED_NOTE);
    out.push_str(&worldspawn(&brushes));
    out.push_str(
        &Meta::cell(
            "authored/hall_straight_buttressed",
            "hall_straight",
            1,
            1,
            7,
        )
        .emit(),
    );
    out.push_str(&tile_cell_default());
    out.push_str(&lateral_port(0, "door", "east_port", 0, 0, 0));
    out.push_str(&lateral_port(3, "door", "west_port", 0, 0, 0));
    out.push_str(&lights);
    out
}

#[must_use]
pub fn hall_turn_60_buttressed() -> String {
    let mut brushes = hall_shell(&[0, 5]);
    brushes.push_str("// Grounded outer-corner masses frame the bend\n");
    for face in [2, 3] {
        brushes.push_str(&band(face, WALL, WALL + 22.0, FLOOR_TOP, 88.0));
    }
    brushes.push_str(&pylon(10.0, FLOOR_TOP, LEVEL - FLOOR_TOP, 30.0, 3.0, 0.0));
    let (fixture, lights) = ceiling_fixture(26.0, 28.0, LEVEL, 15.0, 9.0);
    brushes.push_str(&fixture);
    let mut out =
        String::from("// 60-degree turn variant: supported cove around a full-height pier.\n");
    out.push_str(GENERATED_NOTE);
    out.push_str(&worldspawn(&brushes));
    out.push_str(&Meta::cell("authored/hall_turn_60_buttressed", "hall_turn_60", 1, 1, 7).emit());
    out.push_str(&tile_cell_default());
    out.push_str(&lateral_port(0, "door", "east_port", 0, 0, 0));
    out.push_str(&lateral_port(5, "door", "ne_port", 0, 0, 0));
    out.push_str(&lights);
    out
}

/// A builder, paired with the file stem it must reproduce.
pub type Builder = (&'static str, fn() -> String);

/// Every hall builder, paired with the file it must reproduce.
///
/// The pairing lives here rather than in a central registry so a new hall
/// cannot be added without naming its output - which is what the byte-identity
/// gate iterates.
#[must_use]
pub fn builders() -> Vec<Builder> {
    vec![
        ("hall_straight", hall_straight as fn() -> String),
        ("hall_straight_buttressed", hall_straight_buttressed),
        ("hall_cap", hall_cap),
        ("hall_turn_60", hall_turn_60),
        ("hall_turn_60_buttressed", hall_turn_60_buttressed),
        ("hall_turn_120", hall_turn_120),
        ("hall_junction_3way", hall_junction_3way),
        ("hall_junction_4way", hall_junction_4way),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The gate this whole slice exists for: the Rust must reproduce what the
    /// Python wrote, byte for byte, for every file it claims to own.
    ///
    /// Compared against the *committed corpus* rather than against a fixture,
    /// because the corpus is what the game actually loads. A port that agreed
    /// with a fixture and disagreed with the shipped files would be worse than
    /// no port at all.
    #[test]
    fn every_hall_reproduces_its_committed_file() {
        for (name, build) in builders() {
            let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../assets/tiles/authored")
                .join(format!("{name}.map"));
            // Git may hand back CRLF on Windows; the contract is on content.
            let committed = std::fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("{}: {error}", path.display()))
                .replace("\r\n", "\n");
            let produced = build();
            if committed != produced {
                let at = committed
                    .lines()
                    .zip(produced.lines())
                    .position(|(a, b)| a != b);
                match at {
                    Some(index) => {
                        let expected: Vec<&str> = committed.lines().collect();
                        let actual: Vec<&str> = produced.lines().collect();
                        panic!(
                            "{name}.map diverges at line {}:
  committed: {}
  forge:     {}",
                            index + 1,
                            expected[index],
                            actual[index]
                        );
                    }
                    None => panic!(
                        "{name}.map length differs: committed {} lines, forge {}",
                        committed.lines().count(),
                        produced.lines().count()
                    ),
                }
            }
        }
    }

    /// The builders must actually be wired to distinct outputs. A registry that
    /// pointed two names at one builder would pass the gate above for one of
    /// them and quietly never test the other.
    #[test]
    fn each_hall_builder_produces_a_distinct_file() {
        let built: Vec<String> = builders().into_iter().map(|(_, build)| build()).collect();
        for (index, text) in built.iter().enumerate() {
            for other in built.iter().skip(index + 1) {
                assert_ne!(text, other, "two hall builders produce identical output");
            }
        }
    }
}
