//! The tile forge: parametric authoring of `.map` sources, in Rust.
//!
//! A byte-exact port of `tools/tileforge.py`, which the repository has been
//! carrying alongside `tile_source/geometry.rs` as a second implementation of
//! the same brush math. See [`geometry`] for why that mattered and how the port
//! is gated.

pub mod entities;
pub mod geometry;
pub mod halls;
pub mod liminal;
pub mod probe;
pub mod rooms;
pub mod silos;

/// A builder, paired with the file stem it must reproduce.
pub type Builder = (&'static str, fn() -> String);

/// The line every generated file carries, so a reader who opens one knows not
/// to edit it.
/// **Deliberately stale.** It still names `tools/tileforge.py`, which this
/// module replaced and which is now deleted.
///
/// Correcting it is a one-word change that rewrites all 58 files, and the
/// compiled catalog hash moves with them: measured, `398e3689…` becomes
/// `737ca959…`. That hash gates LAN compatibility, so every peer would have to
/// take the update to keep playing together - a real cost, paid for a comment.
///
/// The line is therefore left wrong until the next change that moves the hash
/// for a reason worth moving it for, at which point this rides along for free.
/// `docs/tile_authoring.md` says where the corpus actually comes from, which is
/// where someone looks when the comment misleads them.
pub const GENERATED_NOTE: &str =
    "// Generated by tools/tileforge.py - edit that script, not this file.\n";

/// Every builder with a named function behind it.
///
/// The liminal family is absent by construction: it is generated from a table
/// rather than one function per file, so it has no `fn() -> String` to name.
/// [`generate_all`] is the complete picture.
#[must_use]
pub fn builders() -> Vec<Builder> {
    let mut all = halls::builders();
    all.extend(silos::builders());
    all.extend(rooms::builders());
    all
}

/// Generate the whole authored corpus: every `(stem, text)` the forge owns.
#[must_use]
pub fn generate_all() -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = builders()
        .into_iter()
        .map(|(name, build)| (name.to_string(), build()))
        .collect();
    out.extend(liminal::generated());
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

/// How much of the authored corpus the forge can generate.
#[must_use]
pub fn coverage() -> (usize, usize) {
    (generate_all().len(), corpus_stems().len())
}

/// The `.map` stems in the committed corpus.
#[must_use]
pub fn corpus_stems() -> Vec<String> {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../assets/tiles/authored");
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut stems: Vec<String> = entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("map"))
        .filter_map(|path| {
            path.file_stem()
                .map(|stem| stem.to_string_lossy().to_string())
        })
        .collect();
    stems.sort();
    stems
}

/// Assert that every builder reproduces its committed file, byte for byte.
///
/// Shared rather than written per family: the comparison is the gate the whole
/// port rests on, and a copy of it that drifted would be a gate that passed for
/// the wrong reason. Compared against the **committed corpus** rather than a
/// fixture, because the corpus is what the game actually loads.
#[cfg(test)]
pub(crate) fn assert_reproduces(builders: &[Builder]) {
    assert!(!builders.is_empty(), "no builders to check");
    for (name, build) in builders {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../assets/tiles/authored")
            .join(format!("{name}.map"));
        // Git may hand back CRLF on Windows; the contract is on content.
        let committed = std::fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("{}: {error}", path.display()))
            .replace("\r\n", "\n");
        let produced = build();
        if committed == produced {
            continue;
        }
        // Name the first divergence rather than dumping the file: a winding bug
        // is one line and is invisible in a wall of coordinates.
        let at = committed
            .lines()
            .zip(produced.lines())
            .position(|(a, b)| a != b);
        match at {
            Some(index) => {
                let expected: Vec<&str> = committed.lines().collect();
                let actual: Vec<&str> = produced.lines().collect();
                panic!(
                    "{name}.map diverges at line {}:\n  committed: {}\n  forge:     {}",
                    index + 1,
                    expected[index],
                    actual[index]
                );
            }
            None => panic!(
                "{name}.map length differs: committed {} lines, forge {}",
                committed.lines().count(),
                produced.lines().count()
            ),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Two builders pointing at one file would leave the other silently
    /// untested while the gate still passed.
    #[test]
    fn every_builder_names_a_distinct_file() {
        let mut names: Vec<&str> = builders().iter().map(|(name, _)| *name).collect();
        let total = names.len();
        names.sort_unstable();
        names.dedup();
        assert_eq!(total, names.len(), "two builders claim the same file");
    }

    /// Every file the forge claims has to exist in the corpus. A typo'd stem
    /// would otherwise fail as a confusing file-not-found deep in a gate.
    #[test]
    fn every_claimed_file_is_in_the_corpus() {
        let corpus = corpus_stems();
        assert!(!corpus.is_empty(), "no authored corpus found");
        for (name, _) in builders() {
            assert!(
                corpus.contains(&name.to_string()),
                "{name} is claimed by the forge but not in the corpus"
            );
        }
    }

    /// The forge must own the whole corpus, exactly.
    ///
    /// Both directions matter. A corpus file with no builder would be silently
    /// abandoned to hand-editing - which is how the FGD drifted - and a builder
    /// with no corpus file would write something nothing reads.
    #[test]
    fn the_forge_covers_the_corpus_exactly() {
        let corpus = corpus_stems();
        assert!(!corpus.is_empty(), "no authored corpus found");

        let mut produced: Vec<String> = generate_all().into_iter().map(|(name, _)| name).collect();
        produced.sort();
        assert_eq!(
            produced, corpus,
            "the forge and the corpus disagree about which files exist"
        );

        let (generated, total) = coverage();
        assert_eq!(generated, total);
    }

    /// Every generated file must survive the importer it was written for.
    ///
    /// Byte-identity says the port reproduces the Python. This says the output
    /// is a module the pipeline actually accepts - which is the property that
    /// still matters if the two ever come apart.
    #[test]
    fn every_generated_module_parses_and_validates() {
        for (name, text) in generate_all() {
            crate::parse_authored_module(&text)
                .unwrap_or_else(|error| panic!("{name} does not validate: {error:?}"));
        }
    }
}
