//! A continuous, multi-level facility generated by constrained Wave Function Collapse.
//!
//! Unlike the legacy observation graph, cells occupy stable world-space coordinates.
//! Rooms, halls and void are WFC states whose face constraints must agree with every
//! neighbour. Observation pins room identity and the exact connecting hall without
//! transitively pinning the room's other, unseen threshold faces.

use std::cmp::{Ordering, Reverse};
use std::collections::{BTreeMap, BTreeSet, BinaryHeap, VecDeque};

use observed_content::ArchitectureRegister;
use observed_core::{PlayerId, SplitMix};

/// Default fixed-step interval between automatic re-collapse requests (five seconds
/// at the game's canonical 60 Hz simulation rate).
pub const DEFAULT_PULSE_TICKS: u32 = 300;

/// Stable coordinate in the module lattice. `level` is the vertical axis; `x` and
/// `z` are the horizontal floor-plan axes.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CellCoord {
    pub x: u16,
    pub z: u16,
    pub level: u8,
}

impl CellCoord {
    pub const fn new(x: u16, z: u16, level: u8) -> Self {
        Self { x, z, level }
    }
}

/// The six faces a module can expose to a neighbour.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum ModuleFace {
    East = 0,
    West = 1,
    South = 2,
    North = 3,
    Up = 4,
    Down = 5,
}

impl ModuleFace {
    pub const ALL: [Self; 6] = [
        Self::East,
        Self::West,
        Self::South,
        Self::North,
        Self::Up,
        Self::Down,
    ];

    pub const fn opposite(self) -> Self {
        match self {
            Self::East => Self::West,
            Self::West => Self::East,
            Self::South => Self::North,
            Self::North => Self::South,
            Self::Up => Self::Down,
            Self::Down => Self::Up,
        }
    }

    pub const fn bit(self) -> u8 {
        1 << self as u8
    }

    pub const fn delta(self) -> (i16, i16, i8) {
        match self {
            Self::East => (1, 0, 0),
            Self::West => (-1, 0, 0),
            Self::South => (0, 1, 0),
            Self::North => (0, -1, 0),
            Self::Up => (0, 0, 1),
            Self::Down => (0, 0, -1),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ModuleSpace {
    Void,
    Room,
    Hall,
}

/// Traversal grammar for a collapsed module. Hall variants always have exactly two
/// open faces, so route choices remain in rooms.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ModuleArchetype {
    Void,
    Room,
    Straight,
    Corner,
    Gantry,
    Climb,
    Shaft,
}

impl ModuleArchetype {
    fn travel_cost(self) -> u32 {
        match self {
            Self::Void => u32::MAX,
            Self::Room => 1_000,
            Self::Straight => 1_000,
            Self::Corner => 1_150,
            Self::Gantry => 1_450,
            Self::Climb => 2_000,
            Self::Shaft => 2_500,
        }
    }
}

/// Stable identity of an instantiated module. A room whose unseen threshold mask
/// changes retains this identity; a deleted/recreated module receives the new
/// generation and key.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ModuleInstanceId {
    pub generation: u32,
    pub key: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ModulePlacement {
    pub coord: CellCoord,
    pub space: ModuleSpace,
    pub archetype: ModuleArchetype,
    pub openings: u8,
    pub architecture: ArchitectureRegister,
    pub instance: ModuleInstanceId,
}

impl ModulePlacement {
    pub fn is_open(&self, face: ModuleFace) -> bool {
        self.openings & face.bit() != 0
    }

    fn geometry_identity(
        &self,
    ) -> (
        ModuleSpace,
        ModuleArchetype,
        ArchitectureRegister,
        ModuleInstanceId,
    ) {
        (self.space, self.archetype, self.architecture, self.instance)
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ThresholdKey {
    pub room: CellCoord,
    pub face: ModuleFace,
}

/// One deterministic simulation-frame observation projection. Presentation or a
/// headless observer computes visibility; the facility consumes only stable IDs.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ObservationFrame {
    pub visible_cells: BTreeSet<CellCoord>,
    /// Includes sealed potential apertures as well as currently open thresholds, so
    /// an unseen wall can become a passage but a visible wall cannot pop away.
    pub visible_thresholds: BTreeSet<ThresholdKey>,
    pub occupied_cells: BTreeMap<PlayerId, CellCoord>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExitClaim {
    pub owner: PlayerId,
    pub path: Vec<CellCoord>,
    pub exit_face: ModuleFace,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Route {
    pub cells: Vec<CellCoord>,
    /// Weighted traversal time in deterministic milli-cost units.
    pub cost_millis: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FullWfcConfig {
    pub cols: u16,
    pub rows: u16,
    pub levels: u8,
    pub min_rooms: usize,
    pub max_rooms: usize,
    pub retry_budget: u32,
    pub pulse_ticks: u32,
}

impl Default for FullWfcConfig {
    fn default() -> Self {
        Self {
            cols: 8,
            rows: 5,
            levels: 3,
            min_rooms: 24,
            max_rooms: 32,
            retry_budget: 64,
            pulse_ticks: DEFAULT_PULSE_TICKS,
        }
    }
}

impl FullWfcConfig {
    pub fn cell_count(self) -> usize {
        usize::from(self.cols) * usize::from(self.rows) * usize::from(self.levels)
    }

    pub fn spawn(self) -> CellCoord {
        CellCoord::new(0, 0, 0)
    }

    pub fn exit(self) -> CellCoord {
        CellCoord::new(self.cols - 1, self.rows - 1, self.levels - 1)
    }

    fn contains(self, coord: CellCoord) -> bool {
        coord.x < self.cols && coord.z < self.rows && coord.level < self.levels
    }

    fn index(self, coord: CellCoord) -> usize {
        usize::from(coord.level) * usize::from(self.cols) * usize::from(self.rows)
            + usize::from(coord.z) * usize::from(self.cols)
            + usize::from(coord.x)
    }

    fn coord(self, index: usize) -> CellCoord {
        let plane = usize::from(self.cols) * usize::from(self.rows);
        let level = index / plane;
        let within = index % plane;
        CellCoord::new(
            (within % usize::from(self.cols)) as u16,
            (within / usize::from(self.cols)) as u16,
            level as u8,
        )
    }

    pub fn neighbor(self, coord: CellCoord, face: ModuleFace) -> Option<CellCoord> {
        let (dx, dz, dl) = face.delta();
        let next = CellCoord::new(
            u16::try_from(i32::from(coord.x) + i32::from(dx)).ok()?,
            u16::try_from(i32::from(coord.z) + i32::from(dz)).ok()?,
            u8::try_from(i16::from(coord.level) + i16::from(dl)).ok()?,
        );
        self.contains(next).then_some(next)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RelayoutCandidate {
    pub generation: u32,
    pub placements: BTreeMap<CellCoord, ModulePlacement>,
    pub changed_cells: BTreeSet<CellCoord>,
    pub attempts: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FullWfcError {
    InvalidConfig,
    RetryBudgetExhausted { attempts: u32 },
    UnsafeChange(CellCoord),
    StaleCandidate,
    MissingPlayerRoute(PlayerId),
}

#[cfg_attr(feature = "bevy", derive(bevy::prelude::Resource))]
#[derive(Clone, Debug)]
pub struct FullWfcWorld {
    pub config: FullWfcConfig,
    pub seed: u64,
    pub generation: u32,
    pub placements: BTreeMap<CellCoord, ModulePlacement>,
    pub observation: ObservationFrame,
    pub exit_claim: Option<ExitClaim>,
    pub reserved_exit_faces: BTreeSet<ModuleFace>,
    pub accepted_pulses: u32,
    pub rejected_pulses: u32,
    pub last_attempts: u32,
}

impl FullWfcWorld {
    pub fn new(seed: u64, config: FullWfcConfig) -> Result<Self, FullWfcError> {
        validate_config(config)?;
        let empty = ObservationFrame::default();
        let (placements, attempts) = collapse(seed, 0, config, None, &empty, &BTreeSet::new())?;
        let mut world = Self {
            config,
            seed,
            generation: 0,
            placements,
            observation: empty,
            exit_claim: None,
            reserved_exit_faces: BTreeSet::new(),
            accepted_pulses: 0,
            rejected_pulses: 0,
            last_attempts: attempts,
        };
        world.refresh_exit_claim();
        Ok(world)
    }

    pub fn spawn(&self) -> CellCoord {
        self.config.spawn()
    }

    pub fn exit(&self) -> CellCoord {
        self.config.exit()
    }

    pub fn placement(&self, coord: CellCoord) -> Option<&ModulePlacement> {
        self.placements.get(&coord)
    }

    pub fn room_count(&self) -> usize {
        self.placements
            .values()
            .filter(|placement| placement.space == ModuleSpace::Room)
            .count()
    }

    pub fn active_cell_count(&self) -> usize {
        self.placements
            .values()
            .filter(|placement| placement.space != ModuleSpace::Void)
            .count()
    }

    pub fn update_observation(&mut self, observation: ObservationFrame) {
        self.observation = observation;
        self.refresh_exit_claim();
    }

    pub fn route(&self, from: CellCoord) -> Option<Route> {
        route_between(
            self.config,
            &self.placements,
            from,
            self.exit(),
            &self.reserved_exit_faces,
            None,
        )
    }

    pub fn spawn_route(&self) -> Option<Route> {
        self.route(self.spawn())
    }

    /// Normalized candle guidance. It intentionally exposes only a scalar: callers
    /// cannot reconstruct the selected A* path from this value.
    pub fn candle_proximity(&self, player_cell: CellCoord) -> f32 {
        let Some(spawn) = self.spawn_route() else {
            return 0.0;
        };
        let Some(player) = self.route(player_cell) else {
            return 0.0;
        };
        if spawn.cost_millis == 0 {
            return 1.0;
        }
        (1.0 - player.cost_millis as f32 / spawn.cost_millis as f32).clamp(0.0, 1.0)
    }

    pub fn propose_relayout(
        &self,
        observation: &ObservationFrame,
    ) -> Result<RelayoutCandidate, FullWfcError> {
        let generation = self.generation.wrapping_add(1);
        let (placements, attempts) = collapse(
            self.seed,
            generation,
            self.config,
            Some(&self.placements),
            observation,
            &self.reserved_exit_faces,
        )?;
        let changed_cells = all_coords(self.config)
            .filter(|coord| self.placements.get(coord) != placements.get(coord))
            .collect();
        Ok(RelayoutCandidate {
            generation,
            placements,
            changed_cells,
            attempts,
        })
    }

    pub fn reject_relayout(&mut self, attempts: u32) {
        self.rejected_pulses = self.rejected_pulses.wrapping_add(1);
        self.last_attempts = attempts;
    }

    pub fn commit_relayout(
        &mut self,
        candidate: RelayoutCandidate,
        latest: ObservationFrame,
    ) -> Result<(), FullWfcError> {
        if candidate.generation != self.generation.wrapping_add(1) {
            return Err(FullWfcError::StaleCandidate);
        }
        for &coord in &candidate.changed_cells {
            let before = &self.placements[&coord];
            let after = &candidate.placements[&coord];
            if !change_is_safe(self.config, before, after, &latest) {
                return Err(FullWfcError::UnsafeChange(coord));
            }
        }

        for (&player, &coord) in &latest.occupied_cells {
            if route_between(
                self.config,
                &candidate.placements,
                coord,
                self.exit(),
                &self.reserved_exit_faces,
                None,
            )
            .is_none()
            {
                return Err(FullWfcError::MissingPlayerRoute(player));
            }
        }

        self.generation = candidate.generation;
        self.placements = candidate.placements;
        self.accepted_pulses = self.accepted_pulses.wrapping_add(1);
        self.last_attempts = candidate.attempts;
        self.observation = latest;
        self.refresh_exit_claim();
        Ok(())
    }

    pub fn connected_active_cells(&self) -> usize {
        active_component(self.config, &self.placements, self.spawn()).len()
    }

    /// Cells whose geometry identity is frozen by current occupancy or observation.
    /// Exposing this projection keeps debug views honest without making them
    /// reimplement the observation-chain rule.
    pub fn pinned_cells(&self) -> BTreeSet<CellCoord> {
        pinned_cells(self.config, &self.placements, &self.observation)
    }

    fn refresh_exit_claim(&mut self) {
        // A claim begins at the first currently observed threshold chain that reaches
        // the exit. It does not require the whole historic spawn route to remain
        // visible: observation is temporary, and only the live terminal chain is the
        // contested resource. Lowest PlayerId then lexical path wins simultaneous
        // claims deterministically.
        self.exit_claim = self
            .observation
            .visible_thresholds
            .iter()
            .filter_map(|&threshold| {
                let chain = threshold_destination_path(self.config, &self.placements, threshold);
                (chain.last().copied() == Some(self.exit())).then(|| {
                    let mut path = vec![threshold.room];
                    path.extend(chain);
                    let previous = path[path.len() - 2];
                    let exit_face = face_between(self.config, self.exit(), previous)
                        .expect("terminal chain cells are adjacent");
                    let owner = self
                        .observation
                        .occupied_cells
                        .iter()
                        .find_map(|(&player, &coord)| (coord == threshold.room).then_some(player))
                        .or_else(|| self.observation.occupied_cells.keys().copied().min())?;
                    Some(ExitClaim {
                        owner,
                        path,
                        exit_face,
                    })
                })?
            })
            .min_by(|a, b| a.owner.cmp(&b.owner).then_with(|| a.path.cmp(&b.path)));

        self.reserved_exit_faces.clear();
        if let Some(claim) = &self.exit_claim {
            let exit = &self.placements[&self.exit()];
            for face in ModuleFace::ALL {
                if exit.is_open(face) && face != claim.exit_face {
                    self.reserved_exit_faces.insert(face);
                }
            }
        }
    }
}

fn validate_config(config: FullWfcConfig) -> Result<(), FullWfcError> {
    if config.cols < 2
        || config.rows < 2
        || config.levels < 2
        || config.min_rooms < 2
        || config.min_rooms > config.max_rooms
        || config.max_rooms >= config.cell_count()
        || config.retry_budget == 0
        || config.pulse_ticks == 0
    {
        return Err(FullWfcError::InvalidConfig);
    }
    Ok(())
}

#[derive(Clone, Copy, Debug)]
struct Variant {
    space: ModuleSpace,
    archetype: ModuleArchetype,
    openings: u8,
    weight: u32,
}

fn catalogue() -> Vec<Variant> {
    let mut variants = vec![Variant {
        space: ModuleSpace::Void,
        archetype: ModuleArchetype::Void,
        openings: 0,
        weight: 4,
    }];
    for mask in 1u8..64 {
        let degree = mask.count_ones();
        let weight = match degree {
            1 => 4,
            2 => 3,
            3 => 2,
            _ => 1,
        };
        variants.push(Variant {
            space: ModuleSpace::Room,
            archetype: ModuleArchetype::Room,
            openings: mask,
            weight,
        });
        if degree == 2 {
            let archetype = hall_archetype(mask);
            variants.push(Variant {
                space: ModuleSpace::Hall,
                archetype,
                openings: mask,
                weight: 5,
            });
            if archetype == ModuleArchetype::Straight {
                variants.push(Variant {
                    space: ModuleSpace::Hall,
                    archetype: ModuleArchetype::Gantry,
                    openings: mask,
                    weight: 1,
                });
            }
        }
    }
    variants
}

fn hall_archetype(mask: u8) -> ModuleArchetype {
    let vertical = mask & (ModuleFace::Up.bit() | ModuleFace::Down.bit());
    if vertical == ModuleFace::Up.bit() | ModuleFace::Down.bit() {
        ModuleArchetype::Shaft
    } else if vertical != 0 {
        ModuleArchetype::Climb
    } else if mask == ModuleFace::East.bit() | ModuleFace::West.bit()
        || mask == ModuleFace::North.bit() | ModuleFace::South.bit()
    {
        ModuleArchetype::Straight
    } else {
        ModuleArchetype::Corner
    }
}

fn collapse(
    seed: u64,
    generation: u32,
    config: FullWfcConfig,
    previous: Option<&BTreeMap<CellCoord, ModulePlacement>>,
    observation: &ObservationFrame,
    reserved_exit_faces: &BTreeSet<ModuleFace>,
) -> Result<(BTreeMap<CellCoord, ModulePlacement>, u32), FullWfcError> {
    let variants = catalogue();
    let previous_pins = previous.map(|layout| pinned_cells(config, layout, observation));

    for attempt in 0..config.retry_budget {
        let attempt_seed = mixed(seed, generation, attempt, 0xF011_C011_A95E_0001);
        let mut rng = SplitMix::new(attempt_seed);
        let forced_edges = forced_route_edges(
            config,
            observation,
            previous,
            previous_pins.as_ref(),
            reserved_exit_faces,
            &mut rng,
        );
        let mut domains = initial_domains(
            config,
            &variants,
            previous,
            previous_pins.as_ref(),
            &forced_edges,
        );
        if !propagate_all(config, &variants, &mut domains) {
            continue;
        }
        if !collapse_domains(config, &variants, &mut domains, &mut rng) {
            continue;
        }
        let mut placements = materialize(
            seed,
            generation,
            config,
            &variants,
            &domains,
            previous,
            previous_pins.as_ref(),
        );
        prune_disconnected(config, &mut placements);

        let room_count = placements
            .values()
            .filter(|placement| placement.space == ModuleSpace::Room)
            .count();
        if !(config.min_rooms..=config.max_rooms).contains(&room_count)
            || !layout_valid(config, &placements, observation, reserved_exit_faces)
        {
            continue;
        }
        return Ok((placements, attempt + 1));
    }

    Err(FullWfcError::RetryBudgetExhausted {
        attempts: config.retry_budget,
    })
}

fn all_coords(config: FullWfcConfig) -> impl Iterator<Item = CellCoord> {
    (0..config.cell_count()).map(move |index| config.coord(index))
}

fn forced_route_edges(
    config: FullWfcConfig,
    observation: &ObservationFrame,
    previous: Option<&BTreeMap<CellCoord, ModulePlacement>>,
    previous_pins: Option<&BTreeSet<CellCoord>>,
    reserved_exit_faces: &BTreeSet<ModuleFace>,
    rng: &mut SplitMix,
) -> BTreeMap<CellCoord, u8> {
    let mut origins = BTreeSet::from([config.spawn()]);
    origins.extend(observation.occupied_cells.values().copied());
    if let Some(pins) = previous_pins {
        origins.extend(pins.iter().copied());
    }

    let mut required = BTreeMap::<CellCoord, u8>::new();
    for origin in origins {
        let path = previous
            .and_then(|placements| {
                route_between(
                    config,
                    placements,
                    origin,
                    config.exit(),
                    reserved_exit_faces,
                    None,
                )
                .map(|route| route.cells)
            })
            .unwrap_or_else(|| randomized_manhattan_path(config, origin, config.exit(), rng));
        for pair in path.windows(2) {
            let face = face_between(config, pair[0], pair[1]).expect("path cells are adjacent");
            *required.entry(pair[0]).or_default() |= face.bit();
            *required.entry(pair[1]).or_default() |= face.opposite().bit();
        }
    }
    required
}

fn randomized_manhattan_path(
    _config: FullWfcConfig,
    start: CellCoord,
    goal: CellCoord,
    rng: &mut SplitMix,
) -> Vec<CellCoord> {
    let mut current = start;
    let mut out = vec![current];
    while current != goal {
        let mut choices = Vec::new();
        if current.x < goal.x {
            choices.push(ModuleFace::East);
        } else if current.x > goal.x {
            choices.push(ModuleFace::West);
        }
        if current.z < goal.z {
            choices.push(ModuleFace::South);
        } else if current.z > goal.z {
            choices.push(ModuleFace::North);
        }
        if current.level < goal.level {
            choices.push(ModuleFace::Up);
        } else if current.level > goal.level {
            choices.push(ModuleFace::Down);
        }
        let face = choices[rng.below(choices.len())];
        let (dx, dz, dl) = face.delta();
        current = CellCoord::new(
            (i32::from(current.x) + i32::from(dx)) as u16,
            (i32::from(current.z) + i32::from(dz)) as u16,
            (i16::from(current.level) + i16::from(dl)) as u8,
        );
        out.push(current);
    }
    out
}

fn initial_domains(
    config: FullWfcConfig,
    variants: &[Variant],
    previous: Option<&BTreeMap<CellCoord, ModulePlacement>>,
    pins: Option<&BTreeSet<CellCoord>>,
    forced: &BTreeMap<CellCoord, u8>,
) -> Vec<Vec<usize>> {
    all_coords(config)
        .map(|coord| {
            let required = forced.get(&coord).copied().unwrap_or(0);
            let previous_placement = previous.and_then(|layout| layout.get(&coord));
            let pinned = pins.is_some_and(|pins| pins.contains(&coord));
            variants
                .iter()
                .enumerate()
                .filter(|(_, variant)| {
                    if ModuleFace::ALL.iter().any(|&face| {
                        config.neighbor(coord, face).is_none() && variant.openings & face.bit() != 0
                    }) {
                        return false;
                    }
                    if variant.openings & required != required {
                        return false;
                    }
                    if coord == config.spawn() || coord == config.exit() {
                        return variant.space == ModuleSpace::Room;
                    }
                    if required.count_ones() > 2 && variant.space != ModuleSpace::Room {
                        return false;
                    }
                    if !pinned {
                        return true;
                    }
                    let Some(previous) = previous_placement else {
                        return true;
                    };
                    match previous.space {
                        ModuleSpace::Room => variant.space == ModuleSpace::Room,
                        ModuleSpace::Hall => {
                            variant.space == ModuleSpace::Hall
                                && variant.openings == previous.openings
                                && variant.archetype == previous.archetype
                        }
                        ModuleSpace::Void => variant.space == ModuleSpace::Void,
                    }
                })
                .map(|(index, _)| index)
                .collect()
        })
        .collect()
}

fn propagate_all(config: FullWfcConfig, variants: &[Variant], domains: &mut [Vec<usize>]) -> bool {
    let mut queue: VecDeque<usize> = (0..domains.len()).collect();
    while let Some(index) = queue.pop_front() {
        let coord = config.coord(index);
        for face in ModuleFace::ALL {
            let Some(neighbor) = config.neighbor(coord, face) else {
                continue;
            };
            let neighbor_index = config.index(neighbor);
            let before = domains[neighbor_index].len();
            let source = domains[index].clone();
            domains[neighbor_index].retain(|&candidate| {
                source
                    .iter()
                    .any(|&other| variants_compatible(variants[other], variants[candidate], face))
            });
            if domains[neighbor_index].is_empty() {
                return false;
            }
            if domains[neighbor_index].len() != before {
                queue.push_back(neighbor_index);
            }
        }
    }
    true
}

fn variants_compatible(a: Variant, b: Variant, face: ModuleFace) -> bool {
    let a_open = a.openings & face.bit() != 0;
    let b_open = b.openings & face.opposite().bit() != 0;
    if a_open != b_open {
        return false;
    }
    if !a_open {
        return true;
    }
    !(a.space == ModuleSpace::Room && b.space == ModuleSpace::Room)
        && a.space != ModuleSpace::Void
        && b.space != ModuleSpace::Void
}

fn collapse_domains(
    config: FullWfcConfig,
    variants: &[Variant],
    domains: &mut [Vec<usize>],
    rng: &mut SplitMix,
) -> bool {
    loop {
        let Some(minimum) = domains
            .iter()
            .filter(|domain| domain.len() > 1)
            .map(Vec::len)
            .min()
        else {
            return domains.iter().all(|domain| domain.len() == 1);
        };
        let choices: Vec<usize> = domains
            .iter()
            .enumerate()
            .filter_map(|(index, domain)| (domain.len() == minimum).then_some(index))
            .collect();
        let cell = choices[rng.below(choices.len())];
        let total: u64 = domains[cell]
            .iter()
            .map(|&variant| u64::from(variants[variant].weight))
            .sum();
        let mut roll = rng.next_u64() % total.max(1);
        let selected = domains[cell]
            .iter()
            .copied()
            .find(|&variant| {
                let weight = u64::from(variants[variant].weight);
                if roll < weight {
                    true
                } else {
                    roll -= weight;
                    false
                }
            })
            .unwrap_or(domains[cell][0]);
        domains[cell] = vec![selected];
        if !propagate_all(config, variants, domains) {
            return false;
        }
    }
}

fn materialize(
    seed: u64,
    generation: u32,
    config: FullWfcConfig,
    variants: &[Variant],
    domains: &[Vec<usize>],
    previous: Option<&BTreeMap<CellCoord, ModulePlacement>>,
    pins: Option<&BTreeSet<CellCoord>>,
) -> BTreeMap<CellCoord, ModulePlacement> {
    all_coords(config)
        .enumerate()
        .map(|(index, coord)| {
            let variant = variants[domains[index][0]];
            let prior = previous.and_then(|layout| layout.get(&coord));
            let pinned = pins.is_some_and(|pins| pins.contains(&coord));
            let retain_room = pinned
                && prior.is_some_and(|placement| {
                    placement.space == ModuleSpace::Room && variant.space == ModuleSpace::Room
                });
            let retain_exact = pinned
                && prior.is_some_and(|placement| {
                    placement.space == variant.space
                        && placement.archetype == variant.archetype
                        && (placement.space == ModuleSpace::Room
                            || placement.openings == variant.openings)
                });
            let architecture =
                if retain_room || retain_exact || coord == config.spawn() || coord == config.exit()
                {
                    prior.map_or_else(
                        || architecture_for(seed, coord, generation),
                        |placement| placement.architecture,
                    )
                } else {
                    architecture_for(seed, coord, generation)
                };
            let instance =
                if retain_room || retain_exact || coord == config.spawn() || coord == config.exit()
                {
                    prior.map_or_else(
                        || instance_for(seed, coord, generation),
                        |placement| placement.instance,
                    )
                } else {
                    instance_for(seed, coord, generation)
                };
            (
                coord,
                ModulePlacement {
                    coord,
                    space: variant.space,
                    archetype: variant.archetype,
                    openings: variant.openings,
                    architecture,
                    instance,
                },
            )
        })
        .collect()
}

fn architecture_for(seed: u64, coord: CellCoord, generation: u32) -> ArchitectureRegister {
    let key = mixed(
        seed,
        generation,
        u32::from(coord.x) | (u32::from(coord.z) << 16),
        u64::from(coord.level),
    );
    ArchitectureRegister::ALL[key as usize % ArchitectureRegister::ALL.len()]
}

fn instance_for(seed: u64, coord: CellCoord, generation: u32) -> ModuleInstanceId {
    ModuleInstanceId {
        generation,
        key: mixed(
            seed,
            generation,
            u32::from(coord.x) | (u32::from(coord.z) << 16),
            u64::from(coord.level) ^ 0x1D_51A7CE,
        ),
    }
}

fn mixed(seed: u64, generation: u32, attempt: u32, domain: u64) -> u64 {
    let mut rng = SplitMix::new(
        seed ^ u64::from(generation).wrapping_mul(0x9E37_79B9_7F4A_7C15)
            ^ u64::from(attempt).wrapping_mul(0xBF58_476D_1CE4_E5B9)
            ^ domain.wrapping_mul(0x94D0_49BB_1331_11EB),
    );
    rng.next_u64()
}

fn prune_disconnected(
    config: FullWfcConfig,
    placements: &mut BTreeMap<CellCoord, ModulePlacement>,
) {
    let keep = active_component(config, placements, config.spawn());
    for (coord, placement) in placements.iter_mut() {
        if placement.space != ModuleSpace::Void && !keep.contains(coord) {
            placement.space = ModuleSpace::Void;
            placement.archetype = ModuleArchetype::Void;
            placement.openings = 0;
        }
    }
}

fn layout_valid(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    observation: &ObservationFrame,
    reserved_exit_faces: &BTreeSet<ModuleFace>,
) -> bool {
    if placements[&config.spawn()].space != ModuleSpace::Room
        || placements[&config.exit()].space != ModuleSpace::Room
        || route_between(
            config,
            placements,
            config.spawn(),
            config.exit(),
            reserved_exit_faces,
            None,
        )
        .is_none()
    {
        return false;
    }
    if active_component(config, placements, config.spawn()).len()
        != placements
            .values()
            .filter(|placement| placement.space != ModuleSpace::Void)
            .count()
    {
        return false;
    }
    for (&player, &coord) in &observation.occupied_cells {
        if route_between(
            config,
            placements,
            coord,
            config.exit(),
            reserved_exit_faces,
            None,
        )
        .is_none()
        {
            let _ = player;
            return false;
        }
    }
    all_edges_match(config, placements)
}

fn all_edges_match(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
) -> bool {
    for coord in all_coords(config) {
        let placement = &placements[&coord];
        if placement.space == ModuleSpace::Hall && placement.openings.count_ones() != 2 {
            return false;
        }
        for face in ModuleFace::ALL {
            let open = placement.is_open(face);
            let Some(neighbor) = config.neighbor(coord, face) else {
                if open {
                    return false;
                }
                continue;
            };
            let other = &placements[&neighbor];
            if open != other.is_open(face.opposite())
                || (open
                    && placement.space == ModuleSpace::Room
                    && other.space == ModuleSpace::Room)
            {
                return false;
            }
        }
    }
    true
}

fn pinned_cells(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    observation: &ObservationFrame,
) -> BTreeSet<CellCoord> {
    let mut pins = BTreeSet::from([config.spawn(), config.exit()]);
    pins.extend(observation.visible_cells.iter().copied());
    pins.extend(observation.occupied_cells.values().copied());
    for &threshold in &observation.visible_thresholds {
        pins.insert(threshold.room);
        pins.extend(threshold_destination_chain(config, placements, threshold));
    }
    pins
}

fn threshold_destination_chain(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    threshold: ThresholdKey,
) -> BTreeSet<CellCoord> {
    threshold_destination_path(config, placements, threshold)
        .into_iter()
        .collect()
}

fn threshold_destination_path(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    threshold: ThresholdKey,
) -> Vec<CellCoord> {
    let mut out = BTreeSet::new();
    let Some(room) = placements.get(&threshold.room) else {
        return Vec::new();
    };
    if room.space != ModuleSpace::Room || !room.is_open(threshold.face) {
        return Vec::new();
    }
    let Some(mut current) = config.neighbor(threshold.room, threshold.face) else {
        return Vec::new();
    };
    let mut previous = threshold.room;
    while out.insert(current) {
        let placement = &placements[&current];
        if placement.space == ModuleSpace::Room {
            break;
        }
        if placement.space != ModuleSpace::Hall {
            break;
        }
        let Some(next) = ModuleFace::ALL.iter().find_map(|&face| {
            if !placement.is_open(face) {
                return None;
            }
            config
                .neighbor(current, face)
                .filter(|&candidate| candidate != previous)
        }) else {
            break;
        };
        previous = current;
        current = next;
    }
    let mut ordered = Vec::with_capacity(out.len());
    let Some(mut current) = config.neighbor(threshold.room, threshold.face) else {
        return ordered;
    };
    let mut previous = threshold.room;
    while out.contains(&current) {
        ordered.push(current);
        let placement = &placements[&current];
        if placement.space == ModuleSpace::Room {
            break;
        }
        let Some(next) = ModuleFace::ALL.iter().find_map(|&face| {
            placement
                .is_open(face)
                .then(|| config.neighbor(current, face))
                .flatten()
                .filter(|&candidate| candidate != previous)
        }) else {
            break;
        };
        previous = current;
        current = next;
    }
    ordered
}

fn change_is_safe(
    config: FullWfcConfig,
    before: &ModulePlacement,
    after: &ModulePlacement,
    latest: &ObservationFrame,
) -> bool {
    let occupied = latest
        .occupied_cells
        .values()
        .any(|&coord| coord == before.coord);
    let visible = latest.visible_cells.contains(&before.coord);
    if before.geometry_identity() != after.geometry_identity() {
        return !occupied && !visible;
    }
    if before.openings == after.openings {
        return true;
    }
    let changed = before.openings ^ after.openings;
    ModuleFace::ALL.iter().all(|&face| {
        changed & face.bit() == 0
            || !latest.visible_thresholds.contains(&ThresholdKey {
                room: before.coord,
                face,
            })
            || config.neighbor(before.coord, face).is_none()
    })
}

fn active_component(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    start: CellCoord,
) -> BTreeSet<CellCoord> {
    if placements
        .get(&start)
        .is_none_or(|placement| placement.space == ModuleSpace::Void)
    {
        return BTreeSet::new();
    }
    let mut seen = BTreeSet::from([start]);
    let mut queue = VecDeque::from([start]);
    while let Some(coord) = queue.pop_front() {
        for (next, _) in live_neighbors(config, placements, coord, &BTreeSet::new(), None) {
            if seen.insert(next) {
                queue.push_back(next);
            }
        }
    }
    seen
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct OpenNode {
    estimated: u32,
    cost: u32,
    coord: CellCoord,
}

impl Ord for OpenNode {
    fn cmp(&self, other: &Self) -> Ordering {
        self.estimated
            .cmp(&other.estimated)
            .then_with(|| self.cost.cmp(&other.cost))
            .then_with(|| self.coord.cmp(&other.coord))
    }
}

impl PartialOrd for OpenNode {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

fn route_between(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    start: CellCoord,
    goal: CellCoord,
    reserved_exit_faces: &BTreeSet<ModuleFace>,
    allowed: Option<&BTreeSet<CellCoord>>,
) -> Option<Route> {
    if placements.get(&start)?.space == ModuleSpace::Void
        || placements.get(&goal)?.space == ModuleSpace::Void
        || allowed.is_some_and(|allowed| !allowed.contains(&start) || !allowed.contains(&goal))
    {
        return None;
    }
    if start == goal {
        return Some(Route {
            cells: vec![start],
            cost_millis: 0,
        });
    }

    let mut open = BinaryHeap::new();
    let mut cost = BTreeMap::from([(start, 0u32)]);
    let mut previous = BTreeMap::new();
    open.push(Reverse(OpenNode {
        estimated: heuristic(start, goal),
        cost: 0,
        coord: start,
    }));

    while let Some(Reverse(node)) = open.pop() {
        if node.coord == goal {
            let mut cells = vec![goal];
            let mut current = goal;
            while current != start {
                current = previous[&current];
                cells.push(current);
            }
            cells.reverse();
            return Some(Route {
                cells,
                cost_millis: node.cost,
            });
        }
        if cost
            .get(&node.coord)
            .is_some_and(|&known| node.cost > known)
        {
            continue;
        }
        for (next, step) in
            live_neighbors(config, placements, node.coord, reserved_exit_faces, allowed)
        {
            let next_cost = node.cost.saturating_add(step);
            if cost.get(&next).is_none_or(|&known| next_cost < known) {
                cost.insert(next, next_cost);
                previous.insert(next, node.coord);
                open.push(Reverse(OpenNode {
                    estimated: next_cost.saturating_add(heuristic(next, goal)),
                    cost: next_cost,
                    coord: next,
                }));
            }
        }
    }
    None
}

fn live_neighbors(
    config: FullWfcConfig,
    placements: &BTreeMap<CellCoord, ModulePlacement>,
    coord: CellCoord,
    reserved_exit_faces: &BTreeSet<ModuleFace>,
    allowed: Option<&BTreeSet<CellCoord>>,
) -> Vec<(CellCoord, u32)> {
    let placement = &placements[&coord];
    ModuleFace::ALL
        .iter()
        .filter_map(|&face| {
            if !placement.is_open(face) {
                return None;
            }
            let next = config.neighbor(coord, face)?;
            if allowed.is_some_and(|allowed| !allowed.contains(&next)) {
                return None;
            }
            let other = &placements[&next];
            if !other.is_open(face.opposite()) {
                return None;
            }
            if (coord == config.exit() && reserved_exit_faces.contains(&face))
                || (next == config.exit() && reserved_exit_faces.contains(&face.opposite()))
            {
                return None;
            }
            Some((next, other.archetype.travel_cost()))
        })
        .collect()
}

fn heuristic(a: CellCoord, b: CellCoord) -> u32 {
    let horizontal = u32::from(a.x.abs_diff(b.x)) + u32::from(a.z.abs_diff(b.z));
    let vertical = u32::from(a.level.abs_diff(b.level));
    horizontal * 1_000 + vertical * 2_000
}

fn face_between(config: FullWfcConfig, a: CellCoord, b: CellCoord) -> Option<ModuleFace> {
    ModuleFace::ALL
        .into_iter()
        .find(|&face| config.neighbor(a, face) == Some(b))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn small_config() -> FullWfcConfig {
        FullWfcConfig {
            cols: 6,
            rows: 4,
            levels: 3,
            min_rooms: 10,
            max_rooms: 24,
            retry_budget: 128,
            pulse_ticks: 60,
        }
    }

    #[test]
    fn same_seed_is_byte_identical_and_uses_all_levels() {
        let a = FullWfcWorld::new(7, small_config()).expect("world");
        let b = FullWfcWorld::new(7, small_config()).expect("world");
        assert_eq!(a.placements, b.placements);
        let route = a.spawn_route().expect("spawn reaches exit");
        assert_eq!(route.cells.first(), Some(&a.spawn()));
        assert_eq!(route.cells.last(), Some(&a.exit()));
        assert!(route.cells.iter().any(|cell| cell.level == 1));
        assert!(route.cells.iter().any(|cell| cell.level == 2));
        assert_eq!(a.connected_active_cells(), a.active_cell_count());
    }

    #[test]
    fn halls_never_branch_and_rooms_never_connect_directly() {
        let world = FullWfcWorld::new(19, small_config()).expect("world");
        for placement in world.placements.values() {
            if placement.space == ModuleSpace::Hall {
                assert_eq!(placement.openings.count_ones(), 2);
            }
            for face in ModuleFace::ALL {
                if !placement.is_open(face) {
                    continue;
                }
                let next = world.config.neighbor(placement.coord, face).unwrap();
                let other = &world.placements[&next];
                assert_ne!(
                    (placement.space, other.space),
                    (ModuleSpace::Room, ModuleSpace::Room)
                );
            }
        }
    }

    #[test]
    fn observation_holds_room_identity_and_exact_hall_but_not_other_room_faces() {
        let mut world = FullWfcWorld::new(33, small_config()).expect("world");
        let route = world.spawn_route().unwrap();
        let room = route
            .cells
            .iter()
            .copied()
            .find(|coord| world.placements[coord].space == ModuleSpace::Room)
            .unwrap();
        let hall = route
            .cells
            .iter()
            .copied()
            .find(|coord| world.placements[coord].space == ModuleSpace::Hall)
            .unwrap();
        let before_room = world.placements[&room].clone();
        let before_hall = world.placements[&hall].clone();
        let frame = ObservationFrame {
            visible_cells: BTreeSet::from([room, hall]),
            occupied_cells: BTreeMap::from([(PlayerId(0), room)]),
            ..Default::default()
        };
        world.update_observation(frame.clone());
        let candidate = world.propose_relayout(&frame).expect("candidate");
        assert_eq!(
            candidate.placements[&room].geometry_identity(),
            before_room.geometry_identity()
        );
        assert_eq!(candidate.placements[&hall], before_hall);
    }

    #[test]
    fn a_visible_threshold_locks_its_hall_chain_and_destination_room() {
        let world = FullWfcWorld::new(41, small_config()).expect("world");
        let route = world.spawn_route().unwrap();
        let room_index = route
            .cells
            .iter()
            .position(|coord| world.placements[coord].space == ModuleSpace::Room)
            .unwrap_or(0);
        let room = route.cells[room_index];
        let next = route.cells[room_index + 1];
        let face = face_between(world.config, room, next).unwrap();
        let frame = ObservationFrame {
            visible_thresholds: BTreeSet::from([ThresholdKey { room, face }]),
            ..Default::default()
        };
        let pins = pinned_cells(world.config, &world.placements, &frame);
        assert!(pins.contains(&room));
        assert!(pins.contains(&next));
        assert!(
            pins.len() >= 3,
            "the far room is included with the hall chain"
        );
    }

    #[test]
    fn relayouts_keep_spawn_and_every_player_connected() {
        for seed in 0..20u64 {
            let mut world = FullWfcWorld::new(seed, small_config()).expect("world");
            let mut player = world.spawn();
            for _ in 0..10 {
                let frame = ObservationFrame {
                    occupied_cells: BTreeMap::from([(PlayerId(0), player)]),
                    visible_cells: BTreeSet::from([player]),
                    ..Default::default()
                };
                world.update_observation(frame.clone());
                let candidate = world.propose_relayout(&frame).expect("candidate");
                world
                    .commit_relayout(candidate, frame)
                    .expect("safe commit");
                let route = world.route(player).expect("player route");
                player = *route.cells.get(1).unwrap_or(&player);
                assert!(world.spawn_route().is_some());
                assert_eq!(world.connected_active_cells(), world.active_cell_count());
            }
        }
    }

    #[test]
    fn candle_brightens_monotonically_along_the_selected_route() {
        let world = FullWfcWorld::new(57, small_config()).expect("world");
        let route = world.spawn_route().unwrap();
        let values: Vec<f32> = route
            .cells
            .iter()
            .map(|&coord| world.candle_proximity(coord))
            .collect();
        assert_eq!(values[0], 0.0);
        assert_eq!(*values.last().unwrap(), 1.0);
        for pair in values.windows(2) {
            assert!(pair[1] + 1.0e-5 >= pair[0], "{values:?}");
        }
    }

    #[test]
    fn an_exit_claim_reserves_every_competing_exit_face() {
        let mut world = FullWfcWorld::new(73, small_config()).expect("world");
        let route = world.spawn_route().unwrap();
        let room_index = route.cells[..route.cells.len() - 1]
            .iter()
            .rposition(|coord| world.placements[coord].space == ModuleSpace::Room)
            .expect("terminal chain starts in a room");
        let room = route.cells[room_index];
        let face = face_between(world.config, room, route.cells[room_index + 1]).unwrap();
        let frame = ObservationFrame {
            visible_cells: BTreeSet::from([room]),
            visible_thresholds: BTreeSet::from([ThresholdKey { room, face }]),
            occupied_cells: BTreeMap::from([(PlayerId(0), room)]),
        };
        world.update_observation(frame);
        let claim = world
            .exit_claim
            .as_ref()
            .expect("observed chain claims exit");
        let exit = &world.placements[&world.exit()];
        for face in ModuleFace::ALL {
            if exit.is_open(face) && face != claim.exit_face {
                assert!(world.reserved_exit_faces.contains(&face));
            }
        }
    }

    #[test]
    fn unsafe_visible_geometry_change_is_rejected() {
        let mut world = FullWfcWorld::new(89, small_config()).expect("world");
        let frame = ObservationFrame::default();
        let mut candidate = world.propose_relayout(&frame).expect("candidate");
        let coord = candidate
            .changed_cells
            .iter()
            .copied()
            .find(|coord| {
                world.placements[coord].geometry_identity()
                    != candidate.placements[coord].geometry_identity()
            })
            .expect("some geometry changes");
        let latest = ObservationFrame {
            visible_cells: BTreeSet::from([coord]),
            ..Default::default()
        };
        assert_eq!(
            world.commit_relayout(candidate.clone(), latest),
            Err(FullWfcError::UnsafeChange(coord))
        );
        candidate.changed_cells.clear();
    }

    /// Release-gate corpus matching the experiment plan. It is ignored in ordinary
    /// workspace runs because it performs 5,000 complete constrained collapses; CI or
    /// an agent can opt in with `cargo test ... extended_default_corpus -- --ignored`.
    #[test]
    #[ignore = "extended 100-seed x 50-pulse WFC corpus"]
    fn extended_default_corpus_keeps_every_runner_route() {
        for seed in 0..100u64 {
            let mut world = FullWfcWorld::new(seed, FullWfcConfig::default())
                .unwrap_or_else(|error| panic!("seed {seed} initial solve failed: {error:?}"));
            let mut player = world.spawn();
            for pulse_index in 0..50 {
                let route = world.route(player).unwrap_or_else(|| {
                    panic!("seed {seed} pulse {pulse_index} lost its pre-pulse route")
                });
                let next = route.cells.get(1).copied();
                let mut visible_thresholds = BTreeSet::new();
                if world.placements[&player].space == ModuleSpace::Room
                    && let Some(next) = next
                {
                    visible_thresholds.insert(ThresholdKey {
                        room: player,
                        face: face_between(world.config, player, next).unwrap(),
                    });
                }
                let frame = ObservationFrame {
                    visible_cells: BTreeSet::from([player]),
                    visible_thresholds,
                    occupied_cells: BTreeMap::from([(PlayerId(0), player)]),
                };
                let candidate = world.propose_relayout(&frame).unwrap_or_else(|error| {
                    panic!("seed {seed} pulse {pulse_index} failed to solve: {error:?}")
                });
                world
                    .commit_relayout(candidate, frame)
                    .unwrap_or_else(|error| {
                        panic!("seed {seed} pulse {pulse_index} failed commit: {error:?}")
                    });
                assert!(
                    world.route(player).is_some(),
                    "seed {seed} pulse {pulse_index}"
                );
                assert_eq!(world.connected_active_cells(), world.active_cell_count());
                player = next.unwrap_or(player);
            }
        }
    }
}
