//! A continuous, multi-level facility generated by constrained Wave Function Collapse.
//! Unlike the legacy observation graph, cells occupy stable world-space coordinates.
//! Rooms, halls and void are WFC states whose face constraints must agree with every
//! neighbour. Observation pins room identity and the exact connecting hall without
//! transitively pinning the room's other, unseen threshold faces.

use std::collections::{BTreeMap, BTreeSet};

use observed_content::ArchitectureRegister;
use observed_core::{CorridorId, PlaceId, PlayerId, RoomId};

mod catalog;
mod collapse;
mod config;
mod constraints;
mod relayout;
mod topology;
mod validate;
pub use catalog::{CorridorInstance, RoomInstance};
use collapse::collapse;
use config::validate_config;
pub use relayout::{RelayoutProgress, RelayoutWork};
use topology::{
    active_component, change_is_safe, exit_reservation_preserves_routes, face_between,
    pinned_cells, route_between, threshold_destination_path,
};

/// Default fixed-step interval between automatic re-collapse requests (five seconds
/// at the game's canonical 60 Hz simulation rate).
pub const DEFAULT_PULSE_TICKS: u32 = 300;

/// Stable coordinate in the module lattice. `level` is the vertical axis; `x` and
/// `z` are the horizontal floor-plan axes.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct CellCoord {
    pub x: u16,
    pub z: u16,
    pub level: u8,
}

impl CellCoord {
    pub const fn new(x: u16, z: u16, level: u8) -> Self {
        Self { x, z, level }
    }
}

/// The six faces a module can expose to a neighbour.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum ModuleFace {
    East = 0,
    West = 1,
    South = 2,
    North = 3,
    Up = 4,
    Down = 5,
}

impl ModuleFace {
    pub const ALL: [Self; 6] = [
        Self::East,
        Self::West,
        Self::South,
        Self::North,
        Self::Up,
        Self::Down,
    ];

    pub const fn opposite(self) -> Self {
        match self {
            Self::East => Self::West,
            Self::West => Self::East,
            Self::South => Self::North,
            Self::North => Self::South,
            Self::Up => Self::Down,
            Self::Down => Self::Up,
        }
    }

    pub const fn bit(self) -> u8 {
        1 << self as u8
    }

    pub const fn delta(self) -> (i16, i16, i8) {
        match self {
            Self::East => (1, 0, 0),
            Self::West => (-1, 0, 0),
            Self::South => (0, 1, 0),
            Self::North => (0, -1, 0),
            Self::Up => (0, 0, 1),
            Self::Down => (0, 0, -1),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ModuleSpace {
    Void,
    Room,
    Hall,
}

/// Traversal grammar for a collapsed module. Branch modules are deliberately rare;
/// a logical corridor is validated at two to four room endpoints.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ModuleArchetype {
    Void,
    Room,
    Straight,
    Corner,
    Junction,
    Gantry,
    Climb,
    Shaft,
}

impl ModuleArchetype {
    fn travel_cost(self) -> u32 {
        match self {
            Self::Void => u32::MAX,
            Self::Room => 1_000,
            Self::Straight => 1_000,
            Self::Corner => 1_150,
            Self::Junction => 1_200,
            Self::Gantry => 1_450,
            Self::Climb => 2_000,
            Self::Shaft => 2_500,
        }
    }
}

/// Stable identity of an instantiated module. A room whose unseen threshold mask
/// changes retains this identity; a deleted/recreated module receives the new
/// generation and key.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ModuleInstanceId {
    pub generation: u32,
    pub key: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ModulePlacement {
    pub coord: CellCoord,
    pub space: ModuleSpace,
    pub archetype: ModuleArchetype,
    pub openings: u8,
    pub architecture: ArchitectureRegister,
    pub instance: ModuleInstanceId,
}

impl ModulePlacement {
    pub fn is_open(&self, face: ModuleFace) -> bool {
        self.openings & face.bit() != 0
    }

    fn geometry_identity(
        &self,
    ) -> (
        ModuleSpace,
        ModuleArchetype,
        ArchitectureRegister,
        ModuleInstanceId,
    ) {
        (self.space, self.archetype, self.architecture, self.instance)
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ThresholdKey {
    pub room: CellCoord,
    pub face: ModuleFace,
}

/// One deterministic simulation-frame observation projection. Presentation or a
/// headless observer computes visibility; the facility consumes only stable IDs.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ObservationFrame {
    pub visible_cells: BTreeSet<CellCoord>,
    /// Includes sealed potential apertures as well as currently open thresholds, so
    /// an unseen wall can become a passage but a visible wall cannot pop away.
    pub visible_thresholds: BTreeSet<ThresholdKey>,
    pub occupied_cells: BTreeMap<PlayerId, CellCoord>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExitClaim {
    pub owner: PlayerId,
    pub path: Vec<CellCoord>,
    pub exit_face: ModuleFace,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Route {
    pub cells: Vec<CellCoord>,
    /// Weighted traversal time in deterministic milli-cost units.
    pub cost_millis: u32,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FullWfcConfig {
    pub cols: u16,
    pub rows: u16,
    pub levels: u8,
    pub min_rooms: usize,
    pub max_rooms: usize,
    pub retry_budget: u32,
    pub pulse_ticks: u32,
    pub min_room_distance: u8,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RelayoutCandidate {
    pub generation: u32,
    pub placements: BTreeMap<CellCoord, ModulePlacement>,
    pub changed_cells: BTreeSet<CellCoord>,
    pub attempts: u32,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FullWfcError {
    InvalidConfig,
    RetryBudgetExhausted { attempts: u32 },
    UnsafeChange(CellCoord),
    StaleCandidate,
    MissingPlayerRoute(PlayerId),
    MissingLandmarkRoute(CellCoord),
}

#[cfg_attr(feature = "bevy", derive(bevy::prelude::Resource))]
#[derive(Clone, Debug)]
pub struct FullWfcWorld {
    pub config: FullWfcConfig,
    pub seed: u64,
    pub generation: u32,
    pub placements: BTreeMap<CellCoord, ModulePlacement>,
    /// Stable logical rooms projected from collapsed room cells. IDs survive any
    /// relayout that retains the room's module instance and are never reused.
    pub rooms: BTreeMap<RoomId, RoomInstance>,
    /// Stable logical corridors projected from connected hall components.
    pub corridors: BTreeMap<CorridorId, CorridorInstance>,
    /// Cells held by authored gameplay landmarks. They are constraints, not
    /// presentation visibility, and therefore never leak into observation.
    pub landmark_cells: BTreeSet<CellCoord>,
    pub observation: ObservationFrame,
    pub exit_claim: Option<ExitClaim>,
    pub reserved_exit_faces: BTreeSet<ModuleFace>,
    pub accepted_pulses: u32,
    pub rejected_pulses: u32,
    pub last_attempts: u32,
    next_room_id: u32,
    next_corridor_id: u32,
}

impl FullWfcWorld {
    pub fn new(seed: u64, config: FullWfcConfig) -> Result<Self, FullWfcError> {
        validate_config(config)?;
        let empty = ObservationFrame::default();
        let (placements, attempts) = collapse(seed, 0, config, None, &empty, &BTreeSet::new())?;
        let mut next_room_id = 0;
        let mut next_corridor_id = 0;
        let projection = catalog::project_catalog(
            seed,
            config,
            &placements,
            None,
            None,
            &mut next_room_id,
            &mut next_corridor_id,
        );
        let mut world = Self {
            config,
            seed,
            generation: 0,
            placements,
            rooms: projection.rooms,
            corridors: projection.corridors,
            landmark_cells: projection.landmark_cells,
            observation: empty,
            exit_claim: None,
            reserved_exit_faces: BTreeSet::new(),
            accepted_pulses: 0,
            rejected_pulses: 0,
            last_attempts: attempts,
            next_room_id,
            next_corridor_id,
        };
        world.refresh_exit_claim();
        Ok(world)
    }

    /// Deterministic content-audit fixture containing every room template and
    /// traversal archetype in one physical WFC lattice. Normal matches retain their
    /// weighted catalog selection.
    pub fn catalog_fixture(seed: u64) -> Result<Self, FullWfcError> {
        for offset in 0..64 {
            let Ok(mut world) = Self::new(seed.wrapping_add(offset), FullWfcConfig::default())
            else {
                continue;
            };
            if world.rooms.len() >= crate::room_def::RoomTemplate::ALL.len()
                && world.corridors.len() >= crate::map_spec::TraversalArchetype::ALL.len()
            {
                catalog::apply_complete_fixture(&mut world.rooms, &mut world.corridors);
                return Ok(world);
            }
        }
        Err(FullWfcError::RetryBudgetExhausted { attempts: 64 })
    }

    pub fn spawn(&self) -> CellCoord {
        self.config.spawn()
    }

    pub fn exit(&self) -> CellCoord {
        self.config.exit()
    }

    pub fn placement(&self, coord: CellCoord) -> Option<&ModulePlacement> {
        self.placements.get(&coord)
    }

    pub fn room(&self, id: RoomId) -> Option<&RoomInstance> {
        self.rooms.get(&id)
    }

    pub fn room_at(&self, coord: CellCoord) -> Option<RoomId> {
        self.rooms
            .values()
            .find_map(|room| (room.coord == coord).then_some(room.id))
    }

    pub fn corridor_at(&self, coord: CellCoord) -> Option<CorridorId> {
        self.corridors
            .values()
            .find_map(|corridor| corridor.cells.contains(&coord).then_some(corridor.id))
    }

    pub fn place_at(&self, coord: CellCoord) -> Option<PlaceId> {
        self.room_at(coord)
            .map(PlaceId::Room)
            .or_else(|| self.corridor_at(coord).map(PlaceId::Corridor))
    }

    /// Deterministic Guardian setback destination. Weighted traversal cost uses the
    /// same route model as the candle and relayout guards; equal-cost rooms choose the
    /// lowest stable ID.
    pub fn farthest_room_from_exit(&self, excluded: &BTreeSet<RoomId>) -> Option<RoomId> {
        self.rooms
            .values()
            .filter(|room| room.role != crate::map_spec::RoomRole::Exit)
            .filter(|room| !excluded.contains(&room.id))
            .filter_map(|room| {
                self.route(room.coord)
                    .map(|route| (route.cost_millis, room.id))
            })
            .max_by(|(a_cost, a_id), (b_cost, b_id)| {
                a_cost.cmp(b_cost).then_with(|| b_id.cmp(a_id))
            })
            .map(|(_, room)| room)
    }

    pub fn room_count(&self) -> usize {
        self.rooms.len()
    }

    pub fn active_cell_count(&self) -> usize {
        self.placements
            .values()
            .filter(|placement| placement.space != ModuleSpace::Void)
            .count()
    }

    pub fn update_observation(&mut self, observation: ObservationFrame) {
        self.observation = observation;
        self.refresh_exit_claim();
    }

    pub fn route(&self, from: CellCoord) -> Option<Route> {
        route_between(
            self.config,
            &self.placements,
            from,
            self.exit(),
            &self.reserved_exit_faces,
            None,
        )
    }

    /// Returns the current weighted route between any two live cells. This is the
    /// shared traversal oracle for simulation systems such as Guardians; callers
    /// must not cache it across a relayout generation.
    pub fn route_between_cells(&self, from: CellCoord, to: CellCoord) -> Option<Route> {
        route_between(
            self.config,
            &self.placements,
            from,
            to,
            &self.reserved_exit_faces,
            None,
        )
    }

    pub fn spawn_route(&self) -> Option<Route> {
        self.route(self.spawn())
    }

    /// Normalized candle guidance. It intentionally exposes only a scalar: callers
    /// cannot reconstruct the selected A* path from this value.
    pub fn candle_proximity(&self, player_cell: CellCoord) -> f32 {
        let Some(spawn) = self.spawn_route() else {
            return 0.0;
        };
        let Some(player) = self.route(player_cell) else {
            return 0.0;
        };
        if spawn.cost_millis == 0 {
            return 1.0;
        }
        (1.0 - player.cost_millis as f32 / spawn.cost_millis as f32).clamp(0.0, 1.0)
    }

    pub fn reject_relayout(&mut self, attempts: u32) {
        self.rejected_pulses = self.rejected_pulses.wrapping_add(1);
        self.last_attempts = attempts;
    }

    pub fn commit_relayout(
        &mut self,
        candidate: RelayoutCandidate,
        latest: ObservationFrame,
    ) -> Result<(), FullWfcError> {
        if candidate.generation != self.generation.wrapping_add(1) {
            return Err(FullWfcError::StaleCandidate);
        }
        for &coord in &candidate.changed_cells {
            let before = &self.placements[&coord];
            let after = &candidate.placements[&coord];
            if !change_is_safe(self.config, before, after, &latest) {
                return Err(FullWfcError::UnsafeChange(coord));
            }
        }

        for (&player, &coord) in &latest.occupied_cells {
            if route_between(
                self.config,
                &candidate.placements,
                coord,
                self.exit(),
                &self.reserved_exit_faces,
                None,
            )
            .is_none()
            {
                return Err(FullWfcError::MissingPlayerRoute(player));
            }
        }
        for &coord in &self.landmark_cells {
            if route_between(
                self.config,
                &candidate.placements,
                coord,
                self.exit(),
                &self.reserved_exit_faces,
                None,
            )
            .is_none()
            {
                return Err(FullWfcError::MissingLandmarkRoute(coord));
            }
        }

        let projection = catalog::project_catalog(
            self.seed,
            self.config,
            &candidate.placements,
            Some(&self.rooms),
            Some(&self.corridors),
            &mut self.next_room_id,
            &mut self.next_corridor_id,
        );
        self.generation = candidate.generation;
        self.placements = candidate.placements;
        self.rooms = projection.rooms;
        self.corridors = projection.corridors;
        self.landmark_cells = projection.landmark_cells;
        self.accepted_pulses = self.accepted_pulses.wrapping_add(1);
        self.last_attempts = candidate.attempts;
        self.observation = latest;
        self.refresh_exit_claim();
        Ok(())
    }

    pub fn connected_active_cells(&self) -> usize {
        active_component(self.config, &self.placements, self.spawn()).len()
    }

    /// Cells whose geometry identity is frozen by current occupancy or observation.
    /// Exposing this projection keeps debug views honest without making them
    /// reimplement the observation-chain rule.
    pub fn pinned_cells(&self) -> BTreeSet<CellCoord> {
        pinned_cells(self.config, &self.placements, &self.observation)
    }

    fn refresh_exit_claim(&mut self) {
        // A claim begins at the first currently observed threshold chain that reaches
        // the exit. It does not require the whole historic spawn route to remain
        // visible: observation is temporary, and only the live terminal chain is the
        // contested resource. Lowest PlayerId then lexical path wins simultaneous
        // claims deterministically.
        let mut protected_origins = self.landmark_cells.clone();
        protected_origins.extend(self.observation.occupied_cells.values().copied());
        self.exit_claim = self
            .observation
            .visible_thresholds
            .iter()
            .filter_map(|&threshold| {
                let chain = threshold_destination_path(self.config, &self.placements, threshold);
                (chain.last().copied() == Some(self.exit())).then(|| {
                    let mut path = vec![threshold.room];
                    path.extend(chain);
                    let previous = path[path.len() - 2];
                    let exit_face = face_between(self.config, self.exit(), previous)
                        .expect("terminal chain cells are adjacent");
                    let owner = self
                        .observation
                        .occupied_cells
                        .iter()
                        .find_map(|(&player, &coord)| (coord == threshold.room).then_some(player))
                        .or_else(|| self.observation.occupied_cells.keys().copied().min())?;
                    Some(ExitClaim {
                        owner,
                        path,
                        exit_face,
                    })
                })?
            })
            .filter(|claim| {
                exit_reservation_preserves_routes(
                    self.config,
                    &self.placements,
                    &protected_origins,
                    claim.exit_face,
                )
            })
            .min_by(|a, b| a.owner.cmp(&b.owner).then_with(|| a.path.cmp(&b.path)));

        self.reserved_exit_faces.clear();
        if let Some(claim) = &self.exit_claim {
            let exit = &self.placements[&self.exit()];
            for face in ModuleFace::ALL {
                if exit.is_open(face) && face != claim.exit_face {
                    self.reserved_exit_faces.insert(face);
                }
            }
        }
    }
}

#[cfg(test)]
mod tests;
