//! The observation room's wall-mounted 3x3 schematic feed, the interactive Guardian
//! Control Console, and the systems that keep both in sync with live game state.
//!
//! **Role-driven, not room-id-driven** (Arc D stage D1 fix): both monitor banks and the
//! console spawn from a [`MapSpec`]'s [`RoomRole::Monitor`] / [`RoomRole::GuardianControl`]
//! rooms — never a literal room id — so any map spec wires up correctly. [`monitor_pages`]
//! partitions the map's rooms across Monitor rooms (9 per room, in room-id order). Each
//! panel is a flush, live schematic generated by [`observation_panel_content`]: footprint
//! outline, doorway stubs, rival dots, anchor halos, and the guardian dot. The pure model
//! reads the simulation but has no access to [`crate::sim::state::MapKnowledge`], so
//! facility-camera knowledge stays diegetic and never leaks into the tac-map.

use bevy::ecs::system::SystemParam;
use bevy::prelude::*;
use observed_core::{RoomId, TeamId};
use observed_facility::map_spec::{MapSpec, RoomRole};
use observed_match::hybrid::HybridMatch;
use observed_style::ObservationPanelRole;

use crate::GameState;
use crate::items::{ItemKind, ItemsState};
use crate::layout::WALL_HEIGHT;
use crate::rivals;
use crate::screens::match_runtime::district_for_place;
use crate::sim::director::MatchDirector;
use crate::sim::state::TeleportState;
use crate::teleport::{self, Place};
use crate::view::assets::{MatchAssets, neon_material};
use crate::view::components::PlaceGeometry;

const MONITOR_COUNT: usize = 9;
const MONITOR_COLUMNS: usize = 3;
const MONITOR_ROWS: usize = 3;
const MONITOR_FACE_OFFSET: f32 = 0.28;
const MONITOR_DEPTH: f32 = 0.06;
const MONITOR_BORDER_DEPTH: f32 = 0.10;
const MONITOR_BORDER_THICKNESS: f32 = 0.045;
const MONITOR_HORIZONTAL_MARGIN: f32 = 0.7;
const MONITOR_VERTICAL_MARGIN: f32 = 0.28;
const MONITOR_GAP: f32 = 0.14;
const MONITOR_CONTENT_Z: f32 = 0.052;
const MONITOR_CONTENT_DEPTH: f32 = 0.012;
const MONITOR_GLYPH_Z: f32 = 0.064;
const MONITOR_GLYPH_DEPTH: f32 = 0.012;
const MONITOR_LINE_THICKNESS: f32 = 0.025;

/// Partition every room of `spec` (sorted by [`RoomId`]) across the map's
/// [`RoomRole::Monitor`] rooms (also in [`RoomId`] order): [`MONITOR_COUNT`] panels per
/// monitor room, each map room appearing on at most one panel across the whole map.
/// Extra panels (a monitor room past the room count, or a map with more rooms than
/// `9 * monitor_room_count` can show) simply stay dark — callers render a page's `Vec`
/// shorter than [`MONITOR_COUNT`] by leaving the remaining wall mounts idle.
pub(crate) fn monitor_pages(spec: &MapSpec) -> Vec<Vec<RoomId>> {
    let mut rooms: Vec<RoomId> = spec.rooms.iter().map(|room| room.id).collect();
    rooms.sort_unstable_by_key(|room| room.0);
    let monitor_rooms = spec.rooms_with_role(RoomRole::Monitor);

    rooms
        .chunks(MONITOR_COUNT)
        .map(<[RoomId]>::to_vec)
        .chain(std::iter::repeat(Vec::new()))
        .take(monitor_rooms.len())
        .collect()
}

/// The panel page for one specific [`RoomRole::Monitor`] room (its position among the
/// map's monitor rooms in [`RoomId`] order selects its [`monitor_pages`] entry). `None`
/// if `room` does not hold the `Monitor` role.
pub(crate) fn monitor_page_for(spec: &MapSpec, room: RoomId) -> Option<Vec<RoomId>> {
    let mut monitor_rooms = spec.rooms_with_role(RoomRole::Monitor);
    monitor_rooms.sort_unstable_by_key(|r| r.0);
    let index = monitor_rooms.iter().position(|&r| r == room)?;
    monitor_pages(spec).into_iter().nth(index)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum ObservationMonitorKind {
    Tether,
    Guardian,
}

#[derive(Clone, Copy, Debug)]
struct WallMonitorMount {
    center: Vec2,
    yaw: f32,
    width: f32,
}

fn monitor_dark_material() -> StandardMaterial {
    let mut material = neon_material(&observed_style::observation_panel(
        ObservationPanelRole::Screen,
    ));
    material.perceptual_roughness = 0.1;
    material.metallic = 0.9;
    material
}

fn wall_inward_normal(a: Vec2, b: Vec2) -> Vec2 {
    let d = (b - a).normalize_or_zero();
    let inward = Vec2::new(-d.y, d.x);
    if inward.dot((a + b) * 0.5) > 0.0 {
        -inward
    } else {
        inward
    }
}

fn wall_monitor_mounts(geom: &teleport::PlaceGeom) -> Vec<WallMonitorMount> {
    let Some(poly) = geom.poly.as_ref() else {
        return Vec::new();
    };
    let mut mounts = Vec::new();
    for i in 0..poly.len() {
        let a = poly[i];
        let b = poly[(i + 1) % poly.len()];
        let edge = b - a;
        let edge_len_sq = edge.length_squared();
        let gap_on_edge = geom.gaps.iter().any(|gap| {
            let t = if edge_len_sq > f32::EPSILON {
                ((gap.center - a).dot(edge) / edge_len_sq).clamp(0.0, 1.0)
            } else {
                0.0
            };
            gap.center.distance(a + edge * t) < 0.08
        });
        if gap_on_edge {
            continue;
        }
        let mid = (a + b) * 0.5;
        let d = b - a;
        let len = d.length();
        if len < MONITOR_HORIZONTAL_MARGIN * 2.0 + 1.0 {
            continue;
        }
        let inward = wall_inward_normal(a, b);
        mounts.push(WallMonitorMount {
            center: mid + inward * MONITOR_FACE_OFFSET,
            yaw: inward.x.atan2(inward.y),
            width: len - MONITOR_HORIZONTAL_MARGIN * 2.0,
        });
    }
    mounts.sort_by(|a, b| {
        a.center
            .y
            .total_cmp(&b.center.y)
            .then_with(|| a.center.x.total_cmp(&b.center.x))
    });
    mounts
}

/// Per-panel entity budget: screen/bezel/labels plus a 13-edge footprint, four doorway
/// stubs, four rival dots, one guardian dot, and a small anchor halo.
#[cfg(test)]
pub(crate) const MONITOR_PANEL_ENTITY_BUDGET: usize = 52;

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct ObservationPanelDoorway {
    pub(crate) slot: teleport::ThresholdSlotId,
    pub(crate) target: RoomId,
    pub(crate) center: Vec2,
    pub(crate) normal: Vec2,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct ObservationPanelAnchor {
    pub(crate) team: TeamId,
    pub(crate) position: Option<Vec2>,
}

/// Pure camera-feed model for one target room. It deliberately contains no Bevy entity,
/// renderer, sighting-ledger, or map-knowledge handle.
#[derive(Clone, Debug, PartialEq)]
pub(crate) struct ObservationPanelContent {
    pub(crate) room: RoomId,
    pub(crate) footprint: Vec<Vec2>,
    pub(crate) doorways: Vec<ObservationPanelDoorway>,
    pub(crate) occupants: Vec<TeamId>,
    pub(crate) anchors: Vec<ObservationPanelAnchor>,
    pub(crate) guardian: Option<Vec2>,
}

pub(crate) fn observation_panel_content(
    seed: u64,
    room: RoomId,
    game: &HybridMatch,
    items: &ItemsState,
    guardian: Option<&crate::guardian::Guardian>,
) -> ObservationPanelContent {
    let connections = crate::sim::nav::connections_for_nav(game, items, room);
    let slots = crate::sim::nav::room_connection_slots(game, items, room, &connections);
    let sealed_slots = crate::sim::nav::sealed_slots_for_room(game, room);
    let target = crate::sim::nav::room_target(game, room, &connections);
    let role = game
        .competitive
        .map_spec
        .as_ref()
        .and_then(|spec| spec.room(room).map(|room| room.role));
    let geom = teleport::room_preview_geom(
        room,
        &connections,
        &slots,
        &sealed_slots,
        target,
        role,
        seed,
    );

    let mut doorways = geom
        .gaps
        .iter()
        .map(|gap| ObservationPanelDoorway {
            slot: gap.threshold.room.slot,
            target: gap.target,
            center: gap.center,
            normal: gap.normal,
        })
        .collect::<Vec<_>>();
    doorways.sort_by_key(|doorway| (doorway.slot, doorway.target.0));

    let mut occupants = rivals::rivals_in_room(&game.competitive, room)
        .into_iter()
        .map(|team| game.competitive.teams[team].id)
        .collect::<Vec<_>>();
    occupants.sort_by_key(|team| team.0);

    let mut anchors = items
        .placed
        .iter()
        .filter(|item| item.kind == ItemKind::AnchorTorch && item.place == Place::Room(room))
        .map(|item| ObservationPanelAnchor {
            team: item.team,
            position: Some(item.pos),
        })
        .collect::<Vec<_>>();
    for anchor in game
        .competitive
        .structure
        .anchors
        .iter()
        .filter(|anchor| anchor.room == room)
    {
        if !anchors
            .iter()
            .any(|candidate| candidate.team == anchor.team)
        {
            anchors.push(ObservationPanelAnchor {
                team: anchor.team,
                position: None,
            });
        }
    }
    anchors.sort_by_key(|anchor| anchor.team.0);

    ObservationPanelContent {
        room,
        footprint: geom.poly.unwrap_or_default(),
        doorways,
        occupants,
        anchors,
        guardian: guardian
            .filter(|guardian| guardian.room == room)
            // The authoritative guardian truth is room-level for this feed. Keeping the
            // warning dot centred avoids rebuilding panel geometry for every cosmetic
            // within-room slide while still moving it between panels in one frame.
            .map(|_| Vec2::ZERO),
    }
}

#[cfg(test)]
pub(crate) fn observation_page_contents(
    seed: u64,
    page: &[RoomId],
    game: &HybridMatch,
    items: &ItemsState,
    guardian: Option<&crate::guardian::Guardian>,
) -> Vec<ObservationPanelContent> {
    page.iter()
        .map(|&room| observation_panel_content(seed, room, game, items, guardian))
        .collect()
}

#[derive(Clone, Debug)]
struct ObservationPanelLayout {
    base: Transform,
    width: f32,
    height: f32,
}

#[derive(Component)]
pub(crate) struct ObservationPanel {
    pub(crate) room: RoomId,
    layout: ObservationPanelLayout,
    materials: ObservationPanelMaterials,
    content: Option<ObservationPanelContent>,
}

#[derive(Clone)]
struct ObservationPanelMaterials {
    footprint: Handle<StandardMaterial>,
    doorway: Handle<StandardMaterial>,
    anchor: Handle<StandardMaterial>,
    guardian: Handle<StandardMaterial>,
}

#[derive(Clone, Copy, Component, Debug, Eq, PartialEq)]
pub(crate) enum ObservationFeedPrimitive {
    Footprint,
    Doorway(teleport::ThresholdSlotId),
    Occupant(TeamId),
    Anchor(TeamId),
    Guardian,
}

#[derive(Component)]
pub(crate) struct ObservationFeedElement {
    pub(crate) room: RoomId,
}

fn panel_bank_mount(geom: &teleport::PlaceGeom) -> Option<WallMonitorMount> {
    // The audit/player view starts near the room centre looking toward -Z. Picking the
    // safe wall with the lowest Z keeps the entire 3x3 bank visible from that natural
    // sightline while remaining deterministic for every seeded 13-gon orientation.
    wall_monitor_mounts(geom).into_iter().min_by(|a, b| {
        a.center
            .y
            .total_cmp(&b.center.y)
            .then_with(|| a.center.x.total_cmp(&b.center.x))
    })
}

/// A deterministic inspection view that frames the complete bank from inside the room.
/// Evidence capture uses the same mount calculation as the renderer, so a seeded polygon
/// rotation can never leave the camera staring at an empty wall again.
pub(crate) fn observation_bank_view(
    geom: &teleport::PlaceGeom,
    y_offset: f32,
) -> Option<Transform> {
    let mount = panel_bank_mount(geom)?;
    let inward = Vec2::new(mount.yaw.sin(), mount.yaw.cos());
    let target = Vec3::new(mount.center.x, y_offset + WALL_HEIGHT * 0.5, mount.center.y);
    let eye = target + Vec3::new(inward.x * 14.0, 0.0, inward.y * 14.0);
    Some(Transform::from_translation(eye).looking_at(target, Vec3::Y))
}

fn panel_grid(mount: WallMonitorMount, y_offset: f32, count: usize) -> Vec<ObservationPanelLayout> {
    let bank_width = mount.width.min(13.2);
    let bank_height = WALL_HEIGHT - MONITOR_VERTICAL_MARGIN * 2.0;
    let panel_width =
        (bank_width - MONITOR_GAP * (MONITOR_COLUMNS - 1) as f32) / MONITOR_COLUMNS as f32;
    let panel_height =
        (bank_height - MONITOR_GAP * (MONITOR_ROWS - 1) as f32) / MONITOR_ROWS as f32;
    let bank = Transform::from_xyz(mount.center.x, y_offset + WALL_HEIGHT * 0.5, mount.center.y)
        .with_rotation(Quat::from_rotation_y(mount.yaw));

    (0..count.min(MONITOR_COUNT))
        .map(|slot| {
            let column = slot % MONITOR_COLUMNS;
            let row = slot / MONITOR_COLUMNS;
            let x = (column as f32 - 1.0) * (panel_width + MONITOR_GAP);
            let y = (1.0 - row as f32) * (panel_height + MONITOR_GAP);
            ObservationPanelLayout {
                base: bank.mul_transform(Transform::from_xyz(x, y, 0.0)),
                width: panel_width,
                height: panel_height,
            }
        })
        .collect()
}

pub(crate) struct ObservationBankSpec<'a> {
    pub(crate) geom: &'a teleport::PlaceGeom,
    pub(crate) y_offset: f32,
    pub(crate) seed: u64,
    pub(crate) room: RoomId,
    pub(crate) page: &'a [RoomId],
}

pub(crate) fn spawn_observation_monitors(
    commands: &mut Commands,
    assets: &MatchAssets,
    materials: &mut Assets<StandardMaterial>,
    spec: ObservationBankSpec<'_>,
) {
    let Some(mount) = panel_bank_mount(spec.geom) else {
        return;
    };
    let border_material = assets.district_accent_materials
        [district_for_place(spec.seed, Place::Room(spec.room)).index()]
    .clone();
    let feed_materials = ObservationPanelMaterials {
        footprint: materials.add(neon_material(&observed_style::observation_panel(
            ObservationPanelRole::Footprint,
        ))),
        doorway: materials.add(neon_material(&observed_style::observation_panel(
            ObservationPanelRole::Doorway,
        ))),
        anchor: materials.add(neon_material(&observed_style::observation_panel(
            ObservationPanelRole::Anchor,
        ))),
        guardian: materials.add(neon_material(&observed_style::observation_panel(
            ObservationPanelRole::Guardian,
        ))),
    };

    for (slot, layout) in panel_grid(mount, spec.y_offset, MONITOR_COUNT)
        .into_iter()
        .enumerate()
    {
        if let Some(&room) = spec.page.get(slot) {
            spawn_observation_panel(
                commands,
                assets,
                materials,
                border_material.clone(),
                feed_materials.clone(),
                slot,
                room,
                layout,
            );
        } else {
            spawn_idle_observation_panel(
                commands,
                assets,
                materials,
                border_material.clone(),
                layout,
            );
        }
    }
}

fn spawn_panel_bezel(
    commands: &mut Commands,
    assets: &MatchAssets,
    border_material: Handle<StandardMaterial>,
    layout: &ObservationPanelLayout,
) {
    let horizontal = Vec3::new(
        layout.width + MONITOR_BORDER_THICKNESS * 2.0,
        MONITOR_BORDER_THICKNESS,
        MONITOR_BORDER_DEPTH,
    );
    let vertical = Vec3::new(
        MONITOR_BORDER_THICKNESS,
        layout.height + MONITOR_BORDER_THICKNESS * 2.0,
        MONITOR_BORDER_DEPTH,
    );
    for (offset, scale) in [
        (Vec3::new(0.0, layout.height * 0.5, 0.035), horizontal),
        (Vec3::new(0.0, -layout.height * 0.5, 0.035), horizontal),
        (Vec3::new(layout.width * 0.5, 0.0, 0.035), vertical),
        (Vec3::new(-layout.width * 0.5, 0.0, 0.035), vertical),
    ] {
        commands.spawn((
            PlaceGeometry,
            DespawnOnExit(GameState::Match),
            Mesh3d(assets.placeholder_mesh.clone()),
            MeshMaterial3d(border_material.clone()),
            layout
                .base
                .mul_transform(Transform::from_translation(offset).with_scale(scale)),
            Name::new("Observation panel bezel"),
        ));
    }
}

fn spawn_idle_observation_panel(
    commands: &mut Commands,
    assets: &MatchAssets,
    materials: &mut Assets<StandardMaterial>,
    border_material: Handle<StandardMaterial>,
    layout: ObservationPanelLayout,
) {
    commands.spawn((
        PlaceGeometry,
        DespawnOnExit(GameState::Match),
        Mesh3d(assets.placeholder_mesh.clone()),
        MeshMaterial3d(materials.add(monitor_dark_material())),
        layout.base.mul_transform(Transform::from_scale(Vec3::new(
            layout.width,
            layout.height,
            MONITOR_DEPTH,
        ))),
        Name::new("Idle observation panel"),
    ));
    spawn_panel_bezel(commands, assets, border_material, &layout);
}

#[allow(clippy::too_many_arguments)]
fn spawn_observation_panel(
    commands: &mut Commands,
    assets: &MatchAssets,
    materials: &mut Assets<StandardMaterial>,
    border_material: Handle<StandardMaterial>,
    feed_materials: ObservationPanelMaterials,
    slot: usize,
    room: RoomId,
    layout: ObservationPanelLayout,
) {
    let screen_material = materials.add(monitor_dark_material());
    commands.spawn((
        PlaceGeometry,
        DespawnOnExit(GameState::Match),
        ObservationPanel {
            room,
            layout: layout.clone(),
            materials: feed_materials,
            content: None,
        },
        Mesh3d(assets.placeholder_mesh.clone()),
        MeshMaterial3d(screen_material),
        layout.base.mul_transform(Transform::from_scale(Vec3::new(
            layout.width,
            layout.height,
            MONITOR_DEPTH,
        ))),
        Name::new(format!("Observation panel R{}", room.0)),
    ));

    spawn_panel_bezel(commands, assets, border_material, &layout);

    let glyph_height = layout.height * 0.22;
    let glyph_width = glyph_height * 0.53;
    let glyph_base = layout.base.mul_transform(Transform::from_xyz(
        -layout.width * 0.37,
        layout.height * 0.33,
        MONITOR_GLYPH_Z,
    ));
    spawn_monitor_room_id_glyph(
        commands,
        assets,
        materials.add(neon_material(&observed_style::observation_panel(
            ObservationPanelRole::Footprint,
        ))),
        glyph_base,
        room,
        ObservationMonitorKind::Tether,
        MonitorGlyphSize {
            width: glyph_width,
            height: glyph_height,
        },
    );

    // These two short status rails retain the legacy diagnostic components while making
    // the state treatment genuinely layered: cyan anchor on the left, red guardian on
    // the right. The schematic itself is unified and always shows both facts.
    let inactive = observed_style::observation_panel(ObservationPanelRole::Screen);
    for (kind, x) in [
        (ObservationMonitorKind::Tether, -layout.width * 0.28),
        (ObservationMonitorKind::Guardian, layout.width * 0.28),
    ] {
        let material = materials.add(neon_material(&inactive));
        let mut rail = commands.spawn((
            PlaceGeometry,
            DespawnOnExit(GameState::Match),
            ObservationMonitorLabelSegment {
                room,
                kind,
                status_only: true,
            },
            Mesh3d(assets.placeholder_mesh.clone()),
            MeshMaterial3d(material),
            layout.base.mul_transform(
                Transform::from_xyz(x, -layout.height * 0.40, MONITOR_GLYPH_Z)
                    .with_scale(Vec3::new(layout.width * 0.22, 0.035, MONITOR_GLYPH_DEPTH)),
            ),
            Name::new(match kind {
                ObservationMonitorKind::Tether => "Observation anchor status rail",
                ObservationMonitorKind::Guardian => "Observation guardian status rail",
            }),
        ));
        match kind {
            ObservationMonitorKind::Tether => {
                rail.insert(TetherCameraMonitor { room });
            }
            ObservationMonitorKind::Guardian => {
                rail.insert(GuardianObservationMonitor { room });
            }
        }
    }

    debug_assert!(slot < MONITOR_COUNT);
}

pub(crate) fn monitor_label(kind: ObservationMonitorKind, room: RoomId, active: bool) -> String {
    let status = match (kind, active) {
        (ObservationMonitorKind::Tether, true) => "ANCHOR LOCKED",
        (ObservationMonitorKind::Tether, false) => "NO ANCHOR",
        (ObservationMonitorKind::Guardian, true) => "GUARDIAN",
        (ObservationMonitorKind::Guardian, false) => "CLEAR",
    };
    format!("R{}\n{status}", room.0)
}

fn monitor_label_segment_material(
    kind: ObservationMonitorKind,
    active: bool,
    status_only: bool,
) -> StandardMaterial {
    let role = match (kind, active, status_only) {
        (ObservationMonitorKind::Tether, true, _) => ObservationPanelRole::Anchor,
        (ObservationMonitorKind::Guardian, true, _) => ObservationPanelRole::Guardian,
        (_, false, true) => ObservationPanelRole::Screen,
        (_, false, false) => ObservationPanelRole::Footprint,
    };
    neon_material(&observed_style::observation_panel(role))
}

#[derive(Clone, Copy)]
struct MonitorGlyphSize {
    width: f32,
    height: f32,
}

fn spawn_monitor_room_id_glyph(
    commands: &mut Commands,
    assets: &MatchAssets,
    material: Handle<StandardMaterial>,
    base: Transform,
    room: RoomId,
    kind: ObservationMonitorKind,
    size: MonitorGlyphSize,
) {
    let MonitorGlyphSize {
        width: glyph_width,
        height: glyph_height,
    } = size;
    let thickness = glyph_width * 0.15;
    let spacing = glyph_width * 0.28;
    let digits = monitor_room_digits(room);
    let glyph_count = 1 + digits.len();
    let total_width = glyph_count as f32 * glyph_width + (glyph_count - 1) as f32 * spacing;
    let start_x = -total_width * 0.5 + glyph_width * 0.5;
    spawn_monitor_letter_r(
        commands,
        assets,
        material.clone(),
        base,
        room,
        kind,
        Vec2::new(start_x, 0.0),
        glyph_width,
        glyph_height,
        thickness,
    );
    for (index, digit) in digits.into_iter().enumerate() {
        spawn_monitor_digit(
            commands,
            assets,
            material.clone(),
            base,
            room,
            kind,
            digit,
            Vec2::new(start_x + (index + 1) as f32 * (glyph_width + spacing), 0.0),
            glyph_width,
            glyph_height,
            thickness,
        );
    }
}

fn monitor_room_digits(room: RoomId) -> Vec<usize> {
    room.0
        .to_string()
        .bytes()
        .map(|digit| (digit - b'0') as usize)
        .collect()
}

#[allow(clippy::too_many_arguments)]
fn spawn_monitor_letter_r(
    commands: &mut Commands,
    assets: &MatchAssets,
    material: Handle<StandardMaterial>,
    base: Transform,
    room: RoomId,
    kind: ObservationMonitorKind,
    origin: Vec2,
    width: f32,
    height: f32,
    thickness: f32,
) {
    let half_h = height * 0.5;
    let half_w = width * 0.5;
    let vertical_h = height * 0.48;
    for (x, y, w, h, rot) in [
        (
            origin.x - half_w,
            origin.y + height * 0.24,
            thickness,
            vertical_h,
            0.0,
        ),
        (
            origin.x - half_w,
            origin.y - height * 0.24,
            thickness,
            vertical_h,
            0.0,
        ),
        (origin.x, origin.y + half_h, width, thickness, 0.0),
        (origin.x, origin.y, width, thickness, 0.0),
        (
            origin.x + half_w,
            origin.y + height * 0.25,
            thickness,
            vertical_h * 0.95,
            0.0,
        ),
        (
            origin.x + width * 0.18,
            origin.y - height * 0.26,
            thickness,
            height * 0.72,
            -std::f32::consts::FRAC_PI_4,
        ),
    ] {
        spawn_monitor_glyph_segment(
            commands,
            assets,
            material.clone(),
            base,
            room,
            kind,
            Vec2::new(x, y),
            Vec2::new(w, h),
            rot,
        );
    }
}

#[allow(clippy::too_many_arguments)]
fn spawn_monitor_digit(
    commands: &mut Commands,
    assets: &MatchAssets,
    material: Handle<StandardMaterial>,
    base: Transform,
    room: RoomId,
    kind: ObservationMonitorKind,
    digit: usize,
    origin: Vec2,
    width: f32,
    height: f32,
    thickness: f32,
) {
    for segment in digit_segments(digit) {
        let (center, size) = segment_rect(*segment, origin, width, height, thickness);
        spawn_monitor_glyph_segment(
            commands,
            assets,
            material.clone(),
            base,
            room,
            kind,
            center,
            size,
            0.0,
        );
    }
}

fn digit_segments(digit: usize) -> &'static [usize] {
    match digit {
        0 => &[0, 1, 2, 3, 4, 5],
        1 => &[1, 2],
        2 => &[0, 1, 6, 4, 3],
        3 => &[0, 1, 6, 2, 3],
        4 => &[5, 6, 1, 2],
        5 => &[0, 5, 6, 2, 3],
        6 => &[0, 5, 6, 4, 2, 3],
        7 => &[0, 1, 2],
        8 => &[0, 1, 2, 3, 4, 5, 6],
        9 => &[0, 1, 2, 3, 5, 6],
        _ => &[],
    }
}

fn segment_rect(
    segment: usize,
    origin: Vec2,
    width: f32,
    height: f32,
    thickness: f32,
) -> (Vec2, Vec2) {
    let half_h = height * 0.5;
    let half_w = width * 0.5;
    let vertical_h = (height - thickness * 3.0) * 0.5;
    match segment {
        0 => (
            Vec2::new(origin.x, origin.y + half_h),
            Vec2::new(width, thickness),
        ),
        1 => (
            Vec2::new(origin.x + half_w, origin.y + height * 0.25),
            Vec2::new(thickness, vertical_h),
        ),
        2 => (
            Vec2::new(origin.x + half_w, origin.y - height * 0.25),
            Vec2::new(thickness, vertical_h),
        ),
        3 => (
            Vec2::new(origin.x, origin.y - half_h),
            Vec2::new(width, thickness),
        ),
        4 => (
            Vec2::new(origin.x - half_w, origin.y - height * 0.25),
            Vec2::new(thickness, vertical_h),
        ),
        5 => (
            Vec2::new(origin.x - half_w, origin.y + height * 0.25),
            Vec2::new(thickness, vertical_h),
        ),
        _ => (origin, Vec2::new(width, thickness)),
    }
}

#[allow(clippy::too_many_arguments)]
fn spawn_monitor_glyph_segment(
    commands: &mut Commands,
    assets: &MatchAssets,
    material: Handle<StandardMaterial>,
    base: Transform,
    room: RoomId,
    kind: ObservationMonitorKind,
    center: Vec2,
    size: Vec2,
    rotation: f32,
) {
    commands.spawn((
        PlaceGeometry,
        DespawnOnExit(GameState::Match),
        ObservationMonitorLabelSegment {
            room,
            kind,
            status_only: false,
        },
        Mesh3d(assets.placeholder_mesh.clone()),
        MeshMaterial3d(material),
        base.mul_transform(
            Transform::from_xyz(center.x, center.y, 0.0)
                .with_rotation(Quat::from_rotation_z(rotation))
                .with_scale(Vec3::new(size.x, size.y, MONITOR_GLYPH_DEPTH)),
        ),
        Name::new("Observation monitor room-id segment"),
    ));
}

#[derive(Component)]
pub(crate) struct TetherCameraMonitor {
    pub(crate) room: RoomId,
}

#[derive(Component)]
pub(crate) struct GuardianObservationMonitor {
    pub(crate) room: RoomId,
}

#[derive(Component)]
pub(crate) struct ObservationMonitorLabelSegment {
    pub(crate) room: RoomId,
    pub(crate) kind: ObservationMonitorKind,
    status_only: bool,
}

#[derive(Component)]
pub(crate) struct GuardianConsole;

#[derive(Clone, Copy)]
struct PanelProjection {
    source_center: Vec2,
    scale: f32,
    panel_center: Vec2,
    half_bounds: Vec2,
}

impl PanelProjection {
    fn for_content(content: &ObservationPanelContent, layout: &ObservationPanelLayout) -> Self {
        let (mut min, mut max) = (Vec2::splat(f32::INFINITY), Vec2::splat(f32::NEG_INFINITY));
        for &point in &content.footprint {
            min = min.min(point);
            max = max.max(point);
        }
        if content.footprint.is_empty() {
            min = -Vec2::ONE;
            max = Vec2::ONE;
        }
        let span = (max - min).max(Vec2::splat(0.001));
        let half_bounds = Vec2::new(layout.width * 0.37, layout.height * 0.29);
        Self {
            source_center: (min + max) * 0.5,
            scale: (half_bounds.x * 2.0 / span.x).min(half_bounds.y * 2.0 / span.y),
            panel_center: Vec2::new(0.0, -layout.height * 0.025),
            half_bounds,
        }
    }

    fn project(self, point: Vec2) -> Vec2 {
        let projected = (point - self.source_center) * self.scale + self.panel_center;
        projected.clamp(
            self.panel_center - self.half_bounds,
            self.panel_center + self.half_bounds,
        )
    }
}

#[allow(clippy::too_many_arguments)]
fn spawn_feed_line(
    commands: &mut Commands,
    assets: &MatchAssets,
    layout: &ObservationPanelLayout,
    material: Handle<StandardMaterial>,
    room: RoomId,
    primitive: ObservationFeedPrimitive,
    start: Vec2,
    end: Vec2,
    thickness: f32,
    z: f32,
    name: &'static str,
) {
    let delta = end - start;
    let length = delta.length();
    if length <= f32::EPSILON {
        return;
    }
    let center = (start + end) * 0.5;
    commands.spawn((
        PlaceGeometry,
        DespawnOnExit(GameState::Match),
        ObservationFeedElement { room },
        primitive,
        Mesh3d(assets.placeholder_mesh.clone()),
        MeshMaterial3d(material),
        layout.base.mul_transform(
            Transform::from_xyz(center.x, center.y, z)
                .with_rotation(Quat::from_rotation_z(delta.y.atan2(delta.x)))
                .with_scale(Vec3::new(length, thickness, MONITOR_CONTENT_DEPTH)),
        ),
        Name::new(name),
    ));
}

#[allow(clippy::too_many_arguments)]
fn spawn_feed_dot(
    commands: &mut Commands,
    assets: &MatchAssets,
    layout: &ObservationPanelLayout,
    material: Handle<StandardMaterial>,
    room: RoomId,
    primitive: ObservationFeedPrimitive,
    center: Vec2,
    radius: f32,
    z: f32,
    name: &'static str,
) {
    commands.spawn((
        PlaceGeometry,
        DespawnOnExit(GameState::Match),
        ObservationFeedElement { room },
        primitive,
        Mesh3d(assets.halo_mesh.clone()),
        MeshMaterial3d(material),
        layout.base.mul_transform(
            Transform::from_xyz(center.x, center.y, z)
                .with_rotation(Quat::from_rotation_x(std::f32::consts::FRAC_PI_2))
                .with_scale(Vec3::new(
                    radius / 0.46,
                    MONITOR_CONTENT_DEPTH / 0.025,
                    radius / 0.46,
                )),
        ),
        Name::new(name),
    ));
}

fn spawn_anchor_halo(
    commands: &mut Commands,
    assets: &MatchAssets,
    layout: &ObservationPanelLayout,
    material: Handle<StandardMaterial>,
    room: RoomId,
    team: TeamId,
    center: Vec2,
) {
    const SEGMENTS: usize = 8;
    let radius = layout.height * 0.105;
    for segment in 0..SEGMENTS {
        let a = segment as f32 * std::f32::consts::TAU / SEGMENTS as f32;
        let b = (segment + 1) as f32 * std::f32::consts::TAU / SEGMENTS as f32;
        spawn_feed_line(
            commands,
            assets,
            layout,
            material.clone(),
            room,
            ObservationFeedPrimitive::Anchor(team),
            center + Vec2::new(a.cos(), a.sin()) * radius,
            center + Vec2::new(b.cos(), b.sin()) * radius,
            MONITOR_LINE_THICKNESS * 0.72,
            MONITOR_CONTENT_Z + 0.004,
            "Observation anchor halo",
        );
    }
}

fn spawn_observation_feed(
    commands: &mut Commands,
    assets: &MatchAssets,
    layout: &ObservationPanelLayout,
    content: &ObservationPanelContent,
    materials: &ObservationPanelMaterials,
) {
    let projection = PanelProjection::for_content(content, layout);
    for edge in 0..content.footprint.len() {
        let a = projection.project(content.footprint[edge]);
        let b = projection.project(content.footprint[(edge + 1) % content.footprint.len()]);
        spawn_feed_line(
            commands,
            assets,
            layout,
            materials.footprint.clone(),
            content.room,
            ObservationFeedPrimitive::Footprint,
            a,
            b,
            MONITOR_LINE_THICKNESS,
            MONITOR_CONTENT_Z,
            "Observation footprint segment",
        );
    }

    for doorway in &content.doorways {
        let center = projection.project(doorway.center);
        let direction = doorway.normal.normalize_or_zero();
        spawn_feed_line(
            commands,
            assets,
            layout,
            materials.doorway.clone(),
            content.room,
            ObservationFeedPrimitive::Doorway(doorway.slot),
            center - direction * layout.height * 0.055,
            center + direction * layout.height * 0.075,
            MONITOR_LINE_THICKNESS * 1.25,
            MONITOR_CONTENT_Z + 0.002,
            "Observation doorway stub",
        );
    }

    let occupant_count = content.occupants.len() as f32;
    for (index, &team) in content.occupants.iter().enumerate() {
        let center = projection.panel_center
            + Vec2::new(
                (index as f32 - (occupant_count - 1.0) * 0.5) * layout.height * 0.115,
                0.0,
            );
        spawn_feed_dot(
            commands,
            assets,
            layout,
            assets.rival_material.clone(),
            content.room,
            ObservationFeedPrimitive::Occupant(team),
            center,
            layout.height * 0.038,
            MONITOR_CONTENT_Z + 0.008,
            "Observation rival dot",
        );
    }

    for (index, anchor) in content.anchors.iter().enumerate() {
        let center = anchor.position.map_or_else(
            || {
                projection.panel_center
                    + Vec2::new(
                        (index as f32 - (content.anchors.len() as f32 - 1.0) * 0.5)
                            * layout.height
                            * 0.16,
                        0.0,
                    )
            },
            |position| projection.project(position),
        );
        spawn_anchor_halo(
            commands,
            assets,
            layout,
            materials.anchor.clone(),
            content.room,
            anchor.team,
            center,
        );
    }

    if let Some(position) = content.guardian {
        spawn_feed_dot(
            commands,
            assets,
            layout,
            materials.guardian.clone(),
            content.room,
            ObservationFeedPrimitive::Guardian,
            projection.project(position),
            layout.height * 0.06,
            MONITOR_CONTENT_Z + 0.012,
            "Observation guardian dot",
        );
    }
}

#[derive(SystemParam)]
pub(crate) struct ObservationSyncParams<'w, 's> {
    assets: Res<'w, MatchAssets>,
    runtime: Res<'w, MatchDirector>,
    items: Res<'w, ItemsState>,
    guardian: Option<Res<'w, crate::guardian::Guardian>>,
    seed: Option<Res<'w, crate::flow::ActiveMatchSeed>>,
    panels: Query<'w, 's, &'static mut ObservationPanel>,
    existing: Query<'w, 's, (Entity, &'static ObservationFeedElement)>,
}

pub(crate) fn sync_observation_monitors(mut commands: Commands, mut params: ObservationSyncParams) {
    let game = params.runtime.live.host_match();
    let seed = params
        .seed
        .map(|seed| seed.0)
        .unwrap_or(crate::flow::MATCH_SEED);
    let guardian = params.guardian.as_deref();

    for mut panel in &mut params.panels {
        let content = observation_panel_content(seed, panel.room, game, &params.items, guardian);
        if panel.content.as_ref() == Some(&content) {
            continue;
        }
        for (entity, element) in &params.existing {
            if element.room == panel.room {
                commands.entity(entity).despawn();
            }
        }
        spawn_observation_feed(
            &mut commands,
            &params.assets,
            &panel.layout,
            &content,
            &panel.materials,
        );
        panel.content = Some(content);
    }
}

pub(crate) fn update_tether_monitors(
    items: Res<ItemsState>,
    runtime: Res<MatchDirector>,
    monitors: Query<(&TetherCameraMonitor, &MeshMaterial3d<StandardMaterial>)>,
    label_segments: Query<(
        &ObservationMonitorLabelSegment,
        &MeshMaterial3d<StandardMaterial>,
    )>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    let game = runtime.live.host_match();
    let is_tethered = |room: RoomId| {
        items
            .placed
            .iter()
            .any(|item| item.kind == ItemKind::AnchorTorch && item.place == Place::Room(room))
            || game
                .competitive
                .structure
                .anchors
                .iter()
                .any(|anchor| anchor.room == room)
    };
    for (monitor, mat_handle) in &monitors {
        if let Some(mat) = materials.get_mut(&mat_handle.0) {
            *mat = monitor_label_segment_material(
                ObservationMonitorKind::Tether,
                is_tethered(monitor.room),
                true,
            );
        }
    }

    for (segment, mat_handle) in &label_segments {
        if segment.kind != ObservationMonitorKind::Tether {
            continue;
        }
        if let Some(mat) = materials.get_mut(&mat_handle.0) {
            *mat = monitor_label_segment_material(
                segment.kind,
                is_tethered(segment.room),
                segment.status_only,
            );
        }
    }
}

pub(crate) fn update_guardian_monitors(
    time: Res<Time>,
    guardian: Option<Res<crate::guardian::Guardian>>,
    monitors: Query<(
        &GuardianObservationMonitor,
        &MeshMaterial3d<StandardMaterial>,
    )>,
    label_segments: Query<(
        &ObservationMonitorLabelSegment,
        &MeshMaterial3d<StandardMaterial>,
    )>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    let guardian_room = guardian.as_ref().map(|guardian| guardian.room);
    let t = time.elapsed_secs();
    for (monitor, mat_handle) in &monitors {
        let is_guardian_here = guardian_room == Some(monitor.room);

        if let Some(mat) = materials.get_mut(&mat_handle.0) {
            *mat = monitor_label_segment_material(
                ObservationMonitorKind::Guardian,
                is_guardian_here,
                true,
            );
            if is_guardian_here {
                // Pulse the style-owned red warning treatment without changing its hue.
                mat.emissive *= 1.0 + (t * 8.0).sin() * 0.18;
            }
        }
    }

    for (segment, mat_handle) in &label_segments {
        if segment.kind != ObservationMonitorKind::Guardian {
            continue;
        }
        let is_guardian_here = guardian_room == Some(segment.room);
        if let Some(mat) = materials.get_mut(&mat_handle.0) {
            *mat =
                monitor_label_segment_material(segment.kind, is_guardian_here, segment.status_only);
            if is_guardian_here {
                mat.emissive *= 1.0 + (t * 8.0).sin() * 0.18;
            }
        }
    }
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn interact_guardian_console(
    keyboard: Res<ButtonInput<KeyCode>>,
    gamepads: Query<&bevy::input::gamepad::Gamepad>,
    tp: Res<TeleportState>,
    runtime: Res<crate::sim::director::MatchDirector>,
    guardian: Option<ResMut<crate::guardian::Guardian>>,
    log: Option<ResMut<crate::guardian::ActionLog>>,
    consoles: Query<&MeshMaterial3d<StandardMaterial>, With<GuardianConsole>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    let Some(mut guardian) = guardian else {
        return;
    };
    let Some(mut log) = log else {
        return;
    };
    let console_room = runtime
        .live
        .host_match()
        .competitive
        .map_spec
        .as_ref()
        .and_then(|spec| spec.role_room(RoomRole::GuardianControl));
    if console_room.is_none_or(|room| tp.place != Place::Room(room)) {
        return;
    }

    // Check distance to console (at Vec2::ZERO in room space)
    let pos = Vec2::new(tp.body.position.x, tp.body.position.z);
    if pos.length() > 2.0 {
        return;
    }

    let interact_pressed = keyboard.just_pressed(KeyCode::KeyE)
        || gamepads
            .iter()
            .any(|pad| pad.just_pressed(GamepadButton::West));

    if interact_pressed {
        // Cycle target: None (Local Player) -> Some(1) -> Some(2) -> Some(3) -> None
        let next_target = match guardian.reassigned_target {
            None => Some(1),
            Some(1) => Some(2),
            Some(2) => Some(3),
            Some(3) => None,
            Some(_) => None,
        };
        guardian.reassigned_target = next_target;

        let msg = match next_target {
            None => "Guardian reassigned to target: Local Player".to_string(),
            Some(t) => format!("Guardian reassigned to target: Rival Team {t}"),
        };
        log.add(msg);
    }

    // Visual feedback: Console active/inactive glow
    let target_active = guardian.reassigned_target.is_some();
    for mat_handle in &consoles {
        if let Some(mat) = materials.get_mut(&mat_handle.0) {
            if target_active {
                mat.base_color = Color::srgb(0.1, 1.0, 0.2);
                mat.emissive = LinearRgba::new(0.5, 5.0, 1.0, 1.0);
            } else {
                mat.base_color = Color::srgb(0.2, 0.2, 0.2);
                mat.emissive = LinearRgba::new(0.2, 0.2, 0.2, 1.0);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use observed_facility::map_spec::sector_relay_v1;

    #[test]
    fn monitor_labels_encode_room_and_state() {
        assert_eq!(
            monitor_label(ObservationMonitorKind::Tether, RoomId(4), true),
            "R4\nANCHOR LOCKED"
        );
        assert_eq!(
            monitor_label(ObservationMonitorKind::Guardian, RoomId(4), true),
            "R4\nGUARDIAN"
        );
        assert_eq!(
            monitor_label(ObservationMonitorKind::Guardian, RoomId(4), false),
            "R4\nCLEAR"
        );
        assert_eq!(
            monitor_label(ObservationMonitorKind::Guardian, RoomId(27), true),
            "R27\nGUARDIAN"
        );
        assert_eq!(monitor_room_digits(RoomId(10)), vec![1, 0]);
        assert_eq!(monitor_room_digits(RoomId(27)), vec![2, 7]);
    }

    #[test]
    fn monitor_yaw_points_the_front_face_inward() {
        let inward = Vec2::new(-0.6, 0.8).normalize();
        let yaw = inward.x.atan2(inward.y);
        let front = Quat::from_rotation_y(yaw) * Vec3::Z;
        assert!((front.x - inward.x).abs() < 0.0001);
        assert!((front.z - inward.y).abs() < 0.0001);
    }

    #[test]
    fn monitor_pages_partition_every_room_at_most_once() {
        for spec in [sector_relay_v1(), crate::map_catalog::default_map_spec(0)] {
            let pages = monitor_pages(&spec);
            let monitor_room_count = spec.rooms_with_role(RoomRole::Monitor).len();
            assert_eq!(
                pages.len(),
                monitor_room_count,
                "one page per Monitor-role room ({})",
                spec.name
            );

            let mut seen = std::collections::BTreeSet::new();
            let mut total = 0;
            for page in &pages {
                assert!(
                    page.len() <= MONITOR_COUNT,
                    "a page never exceeds the physical panel count ({})",
                    spec.name
                );
                for &room in page {
                    assert!(
                        seen.insert(room),
                        "{room:?} must appear on at most one panel across every monitor room ({})",
                        spec.name
                    );
                    total += 1;
                }
            }
            assert!(
                total <= spec.room_count(),
                "never invents rooms ({})",
                spec.name
            );
        }
    }

    #[test]
    fn monitor_pages_are_deterministic() {
        let spec = sector_relay_v1();
        assert_eq!(monitor_pages(&spec), monitor_pages(&spec));
    }

    #[test]
    fn generated_map_monitor_pages_cover_every_room_exactly_once() {
        for seed in [0, 1, 19] {
            let spec = crate::map_catalog::default_map_spec(seed);
            let shown = monitor_pages(&spec)
                .into_iter()
                .flatten()
                .collect::<Vec<_>>();
            let mut expected = spec.rooms.iter().map(|room| room.id).collect::<Vec<_>>();
            expected.sort_unstable_by_key(|room| room.0);
            assert_eq!(shown, expected, "generated map seed {seed}");
        }
    }

    #[test]
    fn panel_grid_is_three_by_three_and_content_stays_inside_the_bezel() {
        let layouts = panel_grid(
            WallMonitorMount {
                center: Vec2::ZERO,
                yaw: 0.0,
                width: 13.2,
            },
            0.0,
            MONITOR_COUNT,
        );
        assert_eq!(layouts.len(), MONITOR_COLUMNS * MONITOR_ROWS);
        for (index, a) in layouts.iter().enumerate() {
            assert!(a.width > 0.0 && a.height > 0.0);
            for b in layouts.iter().skip(index + 1) {
                let delta = a.base.translation - b.base.translation;
                assert!(
                    delta.x.abs() >= a.width + MONITOR_GAP - 0.001
                        || delta.y.abs() >= a.height + MONITOR_GAP - 0.001,
                    "panel rectangles must not overlap"
                );
            }
        }

        let screen_front = MONITOR_DEPTH * 0.5;
        let feed_back = MONITOR_CONTENT_Z - MONITOR_CONTENT_DEPTH * 0.5;
        let guardian_front = MONITOR_CONTENT_Z + 0.012 + MONITOR_CONTENT_DEPTH * 0.5;
        let bezel_front = 0.035 + MONITOR_BORDER_DEPTH * 0.5;
        assert!(
            feed_back > screen_front,
            "feed must sit in front of the screen"
        );
        assert!(
            guardian_front < bezel_front,
            "even the proudest guardian dot must remain behind the bezel face"
        );
        const {
            assert!(MONITOR_FACE_OFFSET - MONITOR_DEPTH * 0.5 > 0.2);
        }
    }

    #[test]
    fn monitor_page_for_matches_the_room_s_slot_in_monitor_pages() {
        let spec = sector_relay_v1();
        let monitor_room = spec
            .rooms_with_role(RoomRole::Monitor)
            .first()
            .copied()
            .expect("sector_relay_v1 has a Monitor room");
        let page = monitor_page_for(&spec, monitor_room).expect("the Monitor room has a page");
        assert_eq!(page, monitor_pages(&spec)[0]);
    }

    #[test]
    fn monitor_page_for_a_non_monitor_room_is_none() {
        let spec = sector_relay_v1();
        let non_monitor = spec
            .rooms
            .iter()
            .find(|room| room.role != RoomRole::Monitor)
            .map(|room| room.id)
            .expect("sector_relay_v1 has non-monitor rooms");
        assert_eq!(monitor_page_for(&spec, non_monitor), None);
    }
}
